myFile = file.choose() #"PoissonCountData.csv"
p2 = read.csv(myFile, header = FALSE)
hist(p2$N, main="Computer Lab Arrivals", xlab = "Counts")
plot(p2$N,type="b",main="Computer Lab Arrivals", ylab = "Count",xlab = "Observation#")
acf(p2$N, main = "ACF Plot for Computer Lab Arrivals")
#install.packages("lattice")
library(lattice) 
splom(p2)
mytable = xtabs(N~Week + Period + Day, data=p2)
summary(mytable)
#install.packages("fitdistrplus")
library(fitdistrplus)
plotdist(p2$N, discrete = TRUE)
fp = fitdist(p2$N, "pois")
summary(fp)
plot(fp)
gofstat(fp)