/*
 *     The KSL provides a discrete-event simulation library for the Kotlin programming language.
 *     Copyright (C) 2026  Manuel D. Rossetti, rossetti@uark.edu
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package ksl.utilities.distributions.fitting.mixture

import kotlin.math.ceil

/**
 *  What a sample says about a component count the analyst proposed.
 *
 *  Three readings rather than two, because "cannot say" is a real outcome here and reporting it as
 *  "not contradicted" would turn a failure to measure into apparent support.
 */
enum class CountEvidence {

    /**
     *  An extra component does not improve the fit by more than it would on data that genuinely has
     *  the hypothesised number. The count the analyst proposed survives this sample.
     *
     *  Not the same as evidence *for* the count. A small sample contradicts very little, so this
     *  reading is weak exactly where the sample is weak, and the adequacy verdict is what says
     *  which case you are in.
     */
    NOT_CONTRADICTED,

    /**
     *  An extra component buys more than chance under the hypothesised count. The data contain
     *  structure that the hypothesised number does not account for.
     */
    CONTRADICTED,

    /**
     *  Too few replicates were usable to say anything. Either the resolution of the bootstrap could
     *  not reach the stated level, or so many replicates failed that the ones that survived are not
     *  a fair sample of the null.
     */
    INCONCLUSIVE
}

/**
 *  A procedure-calibrated test of a hypothesised component count against one more than itself.
 *
 *  **This is not a likelihood-ratio test, and the distinction is not pedantic.** This library does
 *  not maximise the likelihood: it partitions the sorted data, fits a family per group, and refines
 *  the cut positions. The log-likelihood it reports is therefore the value achieved by that
 *  procedure, not the supremum over the k-component family, so the classical statistic is not what
 *  is being computed and no textbook null applies to it. Mixture likelihood ratios are in any case
 *  non-regular — under a k-component null the larger model reaches the truth on a set rather than a
 *  point, the Fisher information is singular, and there is no chi-square limit (Hartigan 1985;
 *  Dacunha-Castelle and Gassiat 1999; Liu and Shao 2003).
 *
 *  The bootstrap is what makes the comparison legitimate. The null is generated by running the
 *  **same procedure** on data drawn from the fitted hypothesised model, so whatever this procedure
 *  falls short of an ideal maximiser by is present on both sides of the comparison and cancels.
 *  What the result means is therefore precise and narrow: *is the improvement this procedure gets
 *  from an extra component larger than the improvement it gets from an extra component on data that
 *  genuinely has the hypothesised number?* That is the analyst's question. It is not a claim about
 *  any ideal estimator, and it should not be reported as one.
 *
 *  The statistic is twice the gain in log-likelihood from the extra component, which is the
 *  quantity `ComponentCountEvidence` already reports per count as its marginal gain. The difference
 *  is what it is compared against: that class charges a fixed algebraic penalty which knows nothing
 *  about the sample, while this one builds the gain's own reference distribution from the data.
 *
 *  @param hypothesisedNumComponents the count under test
 *  @param alternativeNumComponents the count it is tested against, one greater
 *  @param numObservations the size of the sample tested
 *  @param improvementStatistic twice the observed gain in log-likelihood, or null when either fit
 *  was unusable
 *  @param nullStatistics the same quantity on each usable replicate drawn from the fitted
 *  hypothesised model
 *  @param numReplicates how many replicates were attempted, usable or not
 *  @param level the level at which the verdict is read
 */
class ComponentCountTest(
    val hypothesisedNumComponents: Int,
    val alternativeNumComponents: Int,
    val numObservations: Int,
    val improvementStatistic: Double?,
    nullStatistics: DoubleArray,
    val numReplicates: Int,
    val level: Double = defaultLevel
) {

    init {
        require(hypothesisedNumComponents >= 1) { "The hypothesised count must be at least 1" }
        require(alternativeNumComponents == hypothesisedNumComponents + 1) {
            "The alternative must be one more than the hypothesised count"
        }
        require(numObservations >= 0) { "The number of observations cannot be negative" }
        require(numReplicates >= 0) { "The number of replicates cannot be negative" }
        require(level > 0.0 && level < 1.0) { "The level must be strictly between 0 and 1" }
    }

    private val mySortedNull: DoubleArray = nullStatistics.sortedArray()

    /**
     *  The replicate statistics, in ascending order. A defensive copy, so that a caller cannot
     *  reorder the null out from under the quantiles.
     */
    val nullStatistics: DoubleArray
        get() = mySortedNull.copyOf()

    /**
     *  How many replicates produced a usable statistic.
     */
    val numUsable: Int
        get() = mySortedNull.size

    /**
     *  How many replicates were attempted and produced nothing, whether refused before fitting or
     *  fitted to an unusable log-likelihood.
     */
    val numUnusable: Int
        get() = numReplicates - numUsable

    /**
     *  The share of attempted replicates that produced a statistic.
     */
    val usableShare: Double
        get() = if (numReplicates == 0) 0.0 else numUsable.toDouble() / numReplicates

    /**
     *  The bootstrap p-value, or null when there is no statistic or no null to read it against.
     *
     *  Computed as one plus the number of replicates at least as large as the observed, over one
     *  plus the number usable. **The added one is not a rounding convenience.** Without it a finite
     *  bootstrap can return zero, which asserts that the observed value is impossible under the
     *  null — a claim no finite sample of replicates can support. The floor this form imposes is
     *  the honest resolution limit of the number of replicates drawn.
     */
    val pValue: Double?
        get() {
            val observed = improvementStatistic ?: return null
            if (mySortedNull.isEmpty()) return null
            val atLeast = mySortedNull.count { it >= observed }
            return (1.0 + atLeast) / (1.0 + mySortedNull.size)
        }

    /**
     *  The smallest p-value this many replicates could produce, whatever the data say.
     *
     *  A test whose smallest attainable p-value is above its own level cannot reject at that level,
     *  so a reading of not-contradicted from it would be a property of the replicate count rather
     *  than of the sample.
     */
    val smallestAttainablePValue: Double
        get() = if (mySortedNull.isEmpty()) 1.0 else 1.0 / (1.0 + mySortedNull.size)

    /**
     *  Whether the bootstrap has the resolution to reject at this level at all.
     */
    val canReject: Boolean
        get() = smallestAttainablePValue <= level

    /**
     *  The reading, at the stated level.
     *
     *  `INCONCLUSIVE` covers two distinct failures, both of which would otherwise be reported as
     *  not-contradicted and so read as support. The first is resolution: too few usable replicates
     *  for the smallest attainable p-value to reach the level. The second is attrition: when a
     *  large share of replicates failed, the ones that survived are the samples this procedure
     *  found easy, and a null built from them is not the null.
     */
    val verdict: CountEvidence
        get() {
            val p = pValue ?: return CountEvidence.INCONCLUSIVE
            if (!canReject) return CountEvidence.INCONCLUSIVE
            if (usableShare < minimumUsableShare) return CountEvidence.INCONCLUSIVE
            return if (p <= level) CountEvidence.CONTRADICTED else CountEvidence.NOT_CONTRADICTED
        }

    /**
     *  The replicate statistic at the given proportion, by the nearest-rank definition, or null
     *  when no replicate was usable.
     *
     *  @param proportion a value in zero to one
     */
    fun nullQuantile(proportion: Double): Double? {
        require(proportion >= 0.0 && proportion <= 1.0) { "The proportion must be within 0 to 1" }
        if (mySortedNull.isEmpty()) return null
        val rank = ceil(proportion * mySortedNull.size).toInt().coerceIn(1, mySortedNull.size)
        return mySortedNull[rank - 1]
    }

    /**
     *  The quantiles worth showing beside a verdict: the middle of the null and its upper tail.
     */
    fun nullQuantiles(): Map<Double, Double> {
        val proportions = listOf(0.50, 0.90, 0.95, 0.99)
        val out = LinkedHashMap<Double, Double>()
        for (p in proportions) {
            val q = nullQuantile(p) ?: return emptyMap()
            out[p] = q
        }
        return out
    }

    /**
     *  What must accompany any display of this verdict.
     */
    fun caveats(): List<String> = listOf(
        "This is not a likelihood-ratio test. The fitting procedure does not maximise the " +
                "likelihood, so the statistic is the gain this procedure achieves rather than a " +
                "ratio of maxima, and the reading is calibrated to this procedure alone.",
        "The null assumes the fitted mixture at $hypothesisedNumComponents components is the " +
                "truth, so it is the optimistic reading: a poor fit gives a poor null.",
        "Not contradicted is not evidence for the count. A sample that cannot settle the count " +
                "will contradict very little, and the adequacy verdict is what distinguishes the " +
                "two cases.",
        "The p-value cannot fall below ${"%.4f".format(smallestAttainablePValue)} with " +
                "$numUsable usable replicates, whatever the data say."
    )

    /**
     *  A sentence an analyst can read.
     */
    fun explain(): String = when (verdict) {
        CountEvidence.CONTRADICTED ->
            "A sample of $numObservations contradicts $hypothesisedNumComponents components: " +
                    "a ${alternativeNumComponents}th component improves the fit by more than it " +
                    "does on data that genuinely has $hypothesisedNumComponents " +
                    "(p = ${formatP()}). Something in these data is not accounted for by " +
                    "$hypothesisedNumComponents components."
        CountEvidence.NOT_CONTRADICTED ->
            "A sample of $numObservations does not contradict $hypothesisedNumComponents " +
                    "components: a ${alternativeNumComponents}th component buys no more than it " +
                    "does on data that genuinely has $hypothesisedNumComponents " +
                    "(p = ${formatP()}). That is not evidence the count is right, only that " +
                    "these data do not rule it out."
        CountEvidence.INCONCLUSIVE ->
            "A sample of $numObservations cannot say whether $hypothesisedNumComponents " +
                    "components is contradicted. $numUsable of $numReplicates replicates were " +
                    "usable, which is " + (if (!canReject)
                "too few to reject at a level of $level however the data fall."
            else "too small a share for the surviving replicates to stand for the null.")
    }

    private fun formatP(): String = pValue?.let { "%.4f".format(it) } ?: "--"

    override fun toString(): String = buildString {
        appendLine("Component count test: H0 = $hypothesisedNumComponents components, " +
                "against $alternativeNumComponents")
        appendLine("-".repeat(72))
        appendLine("  observations            $numObservations")
        appendLine("  statistic               " +
                (improvementStatistic?.let { "%.4f".format(it) } ?: "not measurable"))
        val quantiles = nullQuantiles()
        if (quantiles.isEmpty()) {
            appendLine("  null                    no usable replicates")
        } else {
            for ((p, q) in quantiles) {
                appendLine("  null ${"%3.0f".format(p * 100)}%                ${"%.4f".format(q)}")
            }
        }
        appendLine("  p-value                 ${formatP()}")
        appendLine("  usable replicates       $numUsable of $numReplicates")
        appendLine("  verdict                 $verdict")
        appendLine()
        appendLine(explain())
        appendLine()
        for (c in caveats()) appendLine("  - $c")
    }

    companion object {

        /**
         *  Replicates drawn when none is specified.
         *
         *  One short of two hundred, so that the p-value's denominator is a round two hundred and
         *  its floor is exactly one in two hundred. The odd count is conventional for bootstrap
         *  tests for that reason rather than by superstition.
         */
        var defaultNumReplicates: Int = 199
            set(value) {
                require(value >= 1) { "There must be at least one replicate" }
                field = value
            }

        /**
         *  The level at which a verdict is read when none is specified.
         */
        var defaultLevel: Double = 0.05
            set(value) {
                require(value > 0.0 && value < 1.0) { "The level must be strictly between 0 and 1" }
                field = value
            }

        /**
         *  The share of attempted replicates that must be usable before a verdict other than
         *  `INCONCLUSIVE` is given.
         *
         *  A half is a judgement rather than a measurement, and it is deliberately blunt. The
         *  concern it encodes is real: replicates fail because a sample was hard to fit, so the
         *  survivors are systematically the easier ones and the null built from them sits too low.
         *  A null that sits too low rejects too readily. Whether a half is the right line is a
         *  question for the validation pass rather than something to settle by argument.
         */
        var minimumUsableShare: Double = 0.5
            set(value) {
                require(value > 0.0 && value <= 1.0) {
                    "The minimum usable share must be within 0 to 1"
                }
                field = value
            }
    }
}
