/*
 * This file is generated by jOOQ.
 */
package ksl.utilities.io.dbutil.ksldbjooq


import kotlin.collections.List

import ksl.utilities.io.dbutil.ksldbjooq.tables.AcrossRepStat
import ksl.utilities.io.dbutil.ksldbjooq.tables.AcrossRepView
import ksl.utilities.io.dbutil.ksldbjooq.tables.BatchStat
import ksl.utilities.io.dbutil.ksldbjooq.tables.BatchStatView
import ksl.utilities.io.dbutil.ksldbjooq.tables.Control
import ksl.utilities.io.dbutil.ksldbjooq.tables.ExpStatRepView
import ksl.utilities.io.dbutil.ksldbjooq.tables.Experiment
import ksl.utilities.io.dbutil.ksldbjooq.tables.ModelElement
import ksl.utilities.io.dbutil.ksldbjooq.tables.PwDiffWithinRepView
import ksl.utilities.io.dbutil.ksldbjooq.tables.RvParameter
import ksl.utilities.io.dbutil.ksldbjooq.tables.SimulationRun
import ksl.utilities.io.dbutil.ksldbjooq.tables.WithinRepCounterStat
import ksl.utilities.io.dbutil.ksldbjooq.tables.WithinRepCounterView
import ksl.utilities.io.dbutil.ksldbjooq.tables.WithinRepResponseView
import ksl.utilities.io.dbutil.ksldbjooq.tables.WithinRepStat
import ksl.utilities.io.dbutil.ksldbjooq.tables.WithinRepView

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class KslDb : SchemaImpl("KSL_DB", DefaultCatalog.DEFAULT_CATALOG) {
    public companion object {

        /**
         * The reference instance of <code>KSL_DB</code>
         */
        val KSL_DB: KslDb = KslDb()
    }

    /**
     * The table <code>KSL_DB.ACROSS_REP_STAT</code>.
     */
    val ACROSS_REP_STAT: AcrossRepStat get() = AcrossRepStat.ACROSS_REP_STAT

    /**
     * The table <code>KSL_DB.ACROSS_REP_VIEW</code>.
     */
    val ACROSS_REP_VIEW: AcrossRepView get() = AcrossRepView.ACROSS_REP_VIEW

    /**
     * The table <code>KSL_DB.BATCH_STAT</code>.
     */
    val BATCH_STAT: BatchStat get() = BatchStat.BATCH_STAT

    /**
     * The table <code>KSL_DB.BATCH_STAT_VIEW</code>.
     */
    val BATCH_STAT_VIEW: BatchStatView get() = BatchStatView.BATCH_STAT_VIEW

    /**
     * The table <code>KSL_DB.CONTROL</code>.
     */
    val CONTROL: Control get() = Control.CONTROL

    /**
     * The table <code>KSL_DB.EXP_STAT_REP_VIEW</code>.
     */
    val EXP_STAT_REP_VIEW: ExpStatRepView get() = ExpStatRepView.EXP_STAT_REP_VIEW

    /**
     * The table <code>KSL_DB.EXPERIMENT</code>.
     */
    val EXPERIMENT: Experiment get() = Experiment.EXPERIMENT

    /**
     * The table <code>KSL_DB.MODEL_ELEMENT</code>.
     */
    val MODEL_ELEMENT: ModelElement get() = ModelElement.MODEL_ELEMENT

    /**
     * The table <code>KSL_DB.PW_DIFF_WITHIN_REP_VIEW</code>.
     */
    val PW_DIFF_WITHIN_REP_VIEW: PwDiffWithinRepView get() = PwDiffWithinRepView.PW_DIFF_WITHIN_REP_VIEW

    /**
     * The table <code>KSL_DB.RV_PARAMETER</code>.
     */
    val RV_PARAMETER: RvParameter get() = RvParameter.RV_PARAMETER

    /**
     * The table <code>KSL_DB.SIMULATION_RUN</code>.
     */
    val SIMULATION_RUN: SimulationRun get() = SimulationRun.SIMULATION_RUN

    /**
     * The table <code>KSL_DB.WITHIN_REP_COUNTER_STAT</code>.
     */
    val WITHIN_REP_COUNTER_STAT: WithinRepCounterStat get() = WithinRepCounterStat.WITHIN_REP_COUNTER_STAT

    /**
     * The table <code>KSL_DB.WITHIN_REP_COUNTER_VIEW</code>.
     */
    val WITHIN_REP_COUNTER_VIEW: WithinRepCounterView get() = WithinRepCounterView.WITHIN_REP_COUNTER_VIEW

    /**
     * The table <code>KSL_DB.WITHIN_REP_RESPONSE_VIEW</code>.
     */
    val WITHIN_REP_RESPONSE_VIEW: WithinRepResponseView get() = WithinRepResponseView.WITHIN_REP_RESPONSE_VIEW

    /**
     * The table <code>KSL_DB.WITHIN_REP_STAT</code>.
     */
    val WITHIN_REP_STAT: WithinRepStat get() = WithinRepStat.WITHIN_REP_STAT

    /**
     * The table <code>KSL_DB.WITHIN_REP_VIEW</code>.
     */
    val WITHIN_REP_VIEW: WithinRepView get() = WithinRepView.WITHIN_REP_VIEW

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        AcrossRepStat.ACROSS_REP_STAT,
        AcrossRepView.ACROSS_REP_VIEW,
        BatchStat.BATCH_STAT,
        BatchStatView.BATCH_STAT_VIEW,
        Control.CONTROL,
        ExpStatRepView.EXP_STAT_REP_VIEW,
        Experiment.EXPERIMENT,
        ModelElement.MODEL_ELEMENT,
        PwDiffWithinRepView.PW_DIFF_WITHIN_REP_VIEW,
        RvParameter.RV_PARAMETER,
        SimulationRun.SIMULATION_RUN,
        WithinRepCounterStat.WITHIN_REP_COUNTER_STAT,
        WithinRepCounterView.WITHIN_REP_COUNTER_VIEW,
        WithinRepResponseView.WITHIN_REP_RESPONSE_VIEW,
        WithinRepStat.WITHIN_REP_STAT,
        WithinRepView.WITHIN_REP_VIEW
    )
}
