/*
 *     The KSL provides a discrete-event simulation library for the Kotlin programming language.
 *     Copyright (C) 2023  Manuel D. Rossetti, rossetti@uark.edu
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package ksl.modeling.elements

import ksl.controls.ControlType
import ksl.controls.KSLControl
import ksl.modeling.variable.RandomVariable
import ksl.modeling.variable.RandomVariableCIfc
import ksl.simulation.KSLEvent
import ksl.simulation.ModelElement
import ksl.utilities.GetValueIfc
import ksl.utilities.random.rvariable.ConstantRV
import ksl.utilities.random.rvariable.RVariableIfc

/**
 * This class allows for the periodic generation of events similar to that
 * achieved by "Create" modules in simulation languages. This class works in
 * conjunction with the EventGeneratorActionIfc which is used to listen and
 * react to the events that are generated by this class.
 *
 * Classes can supply an instance of an EventGeneratorActionIfc to provide the
 * actions that take place when the event occurs. Alternatively, if no
 * EventGeneratorActionIfc is supplied, by default the generator(JSLEvent
 * event) method of this class will be called when the event occurs. Thus,
 * subclasses can simply override this method to provide behavior for when the
 * event occurs. If no EventGeneratorActionIfc is supplied and the method generate()
 * method is not overridden, then the events will still occur; however, no
 * meaningful actions will take place.
 *
 * Of particular note is the use of initial parameters:
 *
 * initial time of first event (default = Constant.ZERO)
 * initial time between events (default = Constant.POSITIVE_INFINITY)
 * initial maximum number of events (default = Long.MAX_VALUE)
 * initial ending time (default = Double.POSITIVE_INFINITY)
 *
 * These parameters control the initial state of the generator at the start
 * of each replication. The generator is re-initialized to these values at
 * the start of each replication. There are also parameters for each of these
 * that can be changed during a replication. The effect of that change
 * is only within the current replication.
 *
 * @param parent the parent model element
 * @param generateAction The action supplies the generation logic for reacting to the generated event.
 * @param timeUntilFirstRV A RandomIfc object that supplies the time until the first event.
 * @param timeBtwEventsRV A RandomIfc object that supplies the time between
 * events. Must not be a RandomIfc that always returns 0.0, if the maximum
 * number of generations is infinite (Long.MAX_VALUE)
 * @param maxNumberOfEvents A long that supplies the maximum number of events to
 * generate. Each time an event is to be scheduled the maximum number of
 * events is checked. If the maximum has been reached, then the generator is
 * turned off. The default is Long.MAX_VALUE. This parameter cannot be
 * Long.MAX_VALUE when the time until next always returns a value of 0.0
 * @param timeOfTheLastEvent A double that supplies a time to stop generating
 * events. When the generator is created, this variable is used to set the
 * ending time of the generator. Each time an event is to be scheduled the
 * ending time is checked. If the time of the next event is past this time,
 * then the generator is turned off and the event won't be scheduled. The
 * default is Double.POSITIVE_INFINITY.
 * @param name the name of the generator
 */
open class EventGenerator(
    parent: ModelElement,
    generateAction: GeneratorActionIfc? = null,
    timeUntilFirstRV: RVariableIfc = ConstantRV.ZERO,
    timeBtwEventsRV: RVariableIfc = ConstantRV.POSITIVE_INFINITY,
    maxNumberOfEvents: Long = Long.MAX_VALUE,
    timeOfTheLastEvent: Double = Double.POSITIVE_INFINITY,
    name: String? = null
) : ModelElement(parent, name), EventGeneratorIfc {

    // The random variables handle the setting of their initial sources.
    // The random variables also handle the resetting of the random sources to initial values prior
    // to the running of replications.

    /**
     * This class allows for the periodic generation of events similar to that
     * achieved by "Create" modules in simulation languages. This class works in
     * conjunction with the EventGeneratorActionIfc which is used to listen and
     * react to the events that are generated by this class.
     *
     * Classes can supply an instance of an EventGeneratorActionIfc to provide the
     * actions that take place when the event occurs. Alternatively, if no
     * EventGeneratorActionIfc is supplied, by default the generator(JSLEvent
     * event) method of this class will be called when the event occurs. Thus,
     * subclasses can simply override this method to provide behavior for when the
     * event occurs. If no EventGeneratorActionIfc is supplied and the method generate()
     * method is not overridden, then the events will still occur; however, no
     * meaningful actions will take place.
     *
     * @param parent the parent model element
     * @param generateAction The action supplies the generation logic for reacting to the generated event.
     * @param arrivalsRV A RVariableIfc object that supplies both the time until the first and
     * the time between events random variables.
     * @param maxNumberOfEvents A long that supplies the maximum number of events to
     * generate. Each time an event is to be scheduled the maximum number of
     * events is checked. If the maximum has been reached, then the generator is
     * turned off. The default is Long.MAX_VALUE. This parameter cannot be
     * Long.MAX_VALUE when the time until next always returns a value of 0.0
     * @param timeOfTheLastEvent A double that supplies a time to stop generating
     * events. When the generator is created, this variable is used to set the
     * ending time of the generator. Each time an event is to be scheduled the
     * ending time is checked. If the time of the next event is past this time,
     * then the generator is turned off and the event won't be scheduled. The
     * default is Double.POSITIVE_INFINITY.
     * @param name the name of the generator
     */
    constructor(
        parent: ModelElement,
        generateAction: GeneratorActionIfc? = null,
        arrivalsRV: RVariableIfc,
        maxNumberOfEvents: Long = Long.MAX_VALUE,
        timeOfTheLastEvent: Double = Double.POSITIVE_INFINITY,
        name: String? = null
    ): this(parent, generateAction,
        timeUntilFirstRV = arrivalsRV,
        timeBtwEventsRV = arrivalsRV,
        maxNumberOfEvents, timeOfTheLastEvent, name
    )

    /**
     * A RandomVariable that uses the time until first random source
     */
    private val myTimeUntilFirstEventRV: RandomVariable = RandomVariable(
        this, timeBtwEventsRV,
        "${this.name}:TimeUntilFirstEventRV"
    )
    override val initialTimeUntilFirstEvent: RandomVariableCIfc
        get() = myTimeUntilFirstEventRV

    init {
        require(maxNumberOfEvents >= 0) { "The maximum number of events to generate was < 0!" }
        if (maxNumberOfEvents == Long.MAX_VALUE) {
            if (timeBtwEventsRV is ConstantRV) {
                //TODO ranges will make this easier to check
                require(timeBtwEventsRV.value != 0.0) { "Maximum number of events is $maxNumberOfEvents and time between events is 0.0" }
            }
        }
        require(timeOfTheLastEvent >= 0) { "The time of the last event was < 0!" }
        //TODO need to implement ranges so that time until first can be checked
    }

    private var myInitialMaxNumEvents: Long = maxNumberOfEvents

    override var initialMaximumNumberOfEvents: Long
        get() = myInitialMaxNumEvents
        set(maxNumEvents) {
            setInitialTimeBetweenEventsAndMaxNumEvents(myTimeBtwEventsRV.initialRandomSource, maxNumEvents)
        }

    /**
     * A random variable for the time between events
     */
    private val myTimeBtwEventsRV: RandomVariable =
        RandomVariable(this, timeBtwEventsRV, "${this.name}:TimeBtwEventsRV")

    override var initialTimeBtwEvents: RVariableIfc
        get() = myTimeBtwEventsRV.initialRandomSource
        set(value) {
            setInitialTimeBetweenEventsAndMaxNumEvents(value, myInitialMaxNumEvents)
        }

    init {
        // now set the initial random sources for the random variables to the supplied values
        // these functions also ensure that the random sources come from the model's provider
        myTimeUntilFirstEventRV.initialRandomSource = timeUntilFirstRV
        setInitialTimeBetweenEventsAndMaxNumEvents(timeBtwEventsRV, maxNumberOfEvents)
    }

    /**
     * The action for the events for generation
     */
    private var generatorAction: GeneratorActionIfc? = generateAction

    /**
     *  Can be used to supply logic to invoke when the generator's
     *  is supposed to generate
     */
    fun generatorAction(action: GeneratorActionIfc?) {
        generatorAction = action
    }

    private var endGeneratorAction: EndGeneratorActionIfc? = null

    /**
     *  Can be used to supply logic to invoke when the generator's
     *  ending time is finite and the generator is turned off.
     */
    fun endGeneratorAction(action: EndGeneratorActionIfc?) {
        endGeneratorAction = action
    }

    /**
     * Determines the priority of the event generator's events The default is
     * DEFAULT_PRIORITY - 1 A lower number implies higher priority.
     */
    var eventPriority = EVENT_PRIORITY

    /**
     * The time to stop generating for the current replication
     */
    override var endingTime: Double = timeOfTheLastEvent
        set(value) {
            require(value >= 0.0) { "The ending time was < 0.0!" }
            if (value < time) {
                turnOffGenerator()
            } else {// now set the time to turn off
                field = value
            }
        }

    /**
     * Used to set the ending time when the generator is initialized
     * at the start of each replication.
     */
    @set:KSLControl(
        controlType = ControlType.DOUBLE,
        name = "initialEndingTime",
        lowerBound = 0.0
    )
    override var initialEndingTime: Double = timeOfTheLastEvent
        set(value) {
            require(value >= 0.0) { "The time until last was < 0.0!" }
            field = value
        }

    /**
     * The next event to be executed for the generator
     */
    private var myNextEvent: KSLEvent<Nothing>? = null

    /**
     * This flag controls whether the generator starts automatically when
     * initialized at the beginning of a replication By default this option is
     * true. If it is changed then it remains at the set value until changed
     * again.
     */
    @set:KSLControl(
        controlType = ControlType.BOOLEAN,
        name = "startOnInitializeOption",
    )
    override var startOnInitializeOption = true

    private val myEventHandler: EventHandler = EventHandler()

    /**
     * indicates whether the generator has been started (turned on)
     */
    override var isStarted = false
        protected set

    // now set the time to turn off

    /**
     * The number of events currently generated during the replication
     */
    override var eventCount: Long = 0
        protected set

    interface ActionStepIfc {
        fun action(action: GeneratorActionIfc): TimeBetweenEventsStepIfc
    }

    interface TimeBetweenEventsStepIfc {
        fun timeBetweenEvents(timeBtwEvents: RVariableIfc): BuildStepIfc
    }

    interface BuildStepIfc {
        fun timeUntilFirst(timeUntilFirst: RVariableIfc): BuildStepIfc
        fun maxNumberOfEvents(maxNum: Long): BuildStepIfc
        fun name(name: String?): BuildStepIfc
        fun timeUntilLastEvent(timeUntilLastEvent: Double): BuildStepIfc
        fun build(): EventGenerator
    }

    private class EventGeneratorBuilder(parent: ModelElement) : ActionStepIfc, TimeBetweenEventsStepIfc,
        BuildStepIfc {
        private val parent: ModelElement
        private var action: GeneratorActionIfc? = null
        private var timeUntilFirst: RVariableIfc = ConstantRV.ZERO
        private var timeBtwEvents: RVariableIfc? = null
        private var maxNum = Long.MAX_VALUE
        private var name: String? = null
        private var timeUntilLastEvent = Double.POSITIVE_INFINITY

        init {
            this.parent = parent
        }

        override fun action(action: GeneratorActionIfc): TimeBetweenEventsStepIfc {
            this.action = action
            return this
        }

        override fun timeUntilFirst(timeUntilFirst: RVariableIfc): BuildStepIfc {
            this.timeUntilFirst = timeUntilFirst
            return this
        }

        override fun timeBetweenEvents(timeBtwEvents: RVariableIfc): BuildStepIfc {
            this.timeBtwEvents = timeBtwEvents
            return this
        }

        override fun maxNumberOfEvents(maxNum: Long): BuildStepIfc {
            require(maxNum > 0) { "The maximum number of events must be > 0." }
            this.maxNum = maxNum
            return this
        }

        override fun name(name: String?): BuildStepIfc {
            this.name = name
            return this
        }

        override fun timeUntilLastEvent(timeUntilLastEvent: Double): BuildStepIfc {
            require(timeUntilLastEvent > 0) { "The time until the last event must be > 0." }
            this.timeUntilLastEvent = timeUntilLastEvent
            return this
        }

        override fun build(): EventGenerator {
            return EventGenerator(parent, action!!, timeUntilFirst, timeBtwEvents!!, maxNum, timeUntilLastEvent, name)
        }
    }

    override fun turnOnGenerator(t: Double) {
        if (isSuspended) {
            return
        }
        if (isDone) {
            return
        }
        if (myMaxNumEvents == 0L) {
            return
        }
        if (eventCount >= myMaxNumEvents) {
            return
        }
        if (myNextEvent != null) {
            return
        }
        isStarted = true
        scheduleFirstEvent(t)
    }

    override fun turnOnGenerator(r: RVariableIfc) {
        turnOnGenerator(r.value)
    }

    override fun turnOffGenerator() {
        isDone = true
        isStarted = false
        if (myNextEvent != null) {
            if (myNextEvent!!.isScheduled) {
                myNextEvent!!.cancel = true
            }
        }
    }

    // must be scheduled and not canceled to be pending
    override val isEventPending: Boolean
        get() = if (myNextEvent == null) {
            false
        } else {
            // must be scheduled and not canceled to be pending
            myNextEvent!!.isScheduled && !myNextEvent!!.cancel
        }

    override fun suspend() {
        isSuspended = true
        if (myNextEvent != null) {
            if (myNextEvent!!.isScheduled) {
                myNextEvent!!.cancel = true
            }
        }
    }

    /**
     * Whether the generator has been suspended
     */
    override var isSuspended: Boolean = false
        protected set

    override fun resume() {
        if (isSuspended) {
            isSuspended = false
            // get the time until next event
            val t: Double = myTimeBtwEventsRV.value
            // check if it is past end time
            if (t + time > endingTime) {
                turnOffGenerator()
            }
            if (!isDone) {
                // I'm not done generating, schedule the event
                myNextEvent = myEventHandler.schedule(t, priority = eventPriority)
            }
        }
    }

    /**
     * Whether the generator is done generating
     */
    override var isDone: Boolean = false
        protected set

    private var myMaxNumEvents: Long = maxNumberOfEvents

    /**
     * The number of events to generate for the current replication
     */
    override var maximumNumberOfEvents: Long = maxNumberOfEvents
        set(maxNum) {
            setTimeBetweenEvents(myTimeBtwEventsRV.randomSource, maxNum)
        }

    /**
     * The time between events for the current replication
     */
    override var timeBetweenEvents: RVariableIfc
        get() = myTimeBtwEventsRV.randomSource
        set(timeUntilNext) {
            setTimeBetweenEvents(timeUntilNext, myMaxNumEvents)
        }

    override fun setTimeBetweenEvents(timeBtwEvents: RVariableIfc, maxNumEvents: Long) {
        require(maxNumEvents >= 0) { "The maximum number of actions was < 0!" }
        if (maxNumEvents == Long.MAX_VALUE) {
            if (timeBtwEvents is ConstantRV) {
                require(timeBtwEvents.value != 0.0) { "Maximum number of actions is infinite and time between actions is 0.0" }
            }
        }
        // time btw events is okay and max num events is okay
        myMaxNumEvents = maxNumEvents
        myTimeBtwEventsRV.randomSource = timeBtwEvents
        // if number of events is >= desired number of events, turn off the generator
        if (eventCount >= maxNumEvents) {
            turnOffGenerator()
        }
    }

    final override fun setInitialTimeBetweenEventsAndMaxNumEvents(
        initialTimeBtwEvents: RVariableIfc,
        initialMaxNumEvents: Long
    ) {
        require(model.isNotRunning) { "The model should not be running when changing the initial time between events or the initial maximum number of events." }
        require(initialMaxNumEvents >= 0) { "The maximum number of events to generate was < 0!" }
        if (initialMaxNumEvents == Long.MAX_VALUE) {
            if (initialTimeBtwEvents is ConstantRV) {
                require(initialTimeBtwEvents.value > 0.0) { "Maximum number of events is infinite and time between events <= 0.0" }
            }
        }
        myInitialMaxNumEvents = initialMaxNumEvents
        myTimeBtwEventsRV.initialRandomSource = initialTimeBtwEvents
    }

    override fun initialize() {
        isDone = false
        isStarted = false
        isSuspended = false
        eventCount = 0
        myNextEvent = null
        // set ending time based on the value to be used for each replication
        endingTime = initialEndingTime
        if (startOnInitializeOption) {
            if (myMaxNumEvents > 0) {
                scheduleFirstEvent(myTimeUntilFirstEventRV)
            }
        }
        if (endingTime.isFinite()) {
            schedule(this::endGeneratorAction, endingTime)
        }
    }

    @Suppress("UNUSED_PARAMETER")
    private fun endGeneratorAction(event: KSLEvent<Nothing>) {
        turnOffGenerator()
        endGeneratorAction?.endGeneration(this) ?: endGeneration()
    }

    /**
     * Schedules the first event at current time + r.getValue()
     *
     * @param r the time to the first event
     */
    private fun scheduleFirstEvent(r: GetValueIfc) {
        scheduleFirstEvent(r.value)
    }

    /**
     * Schedules the first event at current time + t
     *
     * @param t the time to the first event
     */
    private fun scheduleFirstEvent(t: Double) {
        if (t + time > endingTime) {
            turnOffGenerator()
        }
        if (!isDone) {
            // I'm not done generating, schedule the first event
            myNextEvent = myEventHandler.schedule(t, priority = eventPriority)
        }
    }

    /**
     * Increments the number of actions and checks if the number of actions is
     * greater than the maximum number of actions. If so, the generator is told
     * to shut down.
     */
    private fun incrementNumberOfEvents() {
        eventCount++
        if (eventCount > myMaxNumEvents) {
            turnOffGenerator()
        }
    }

    private inner class EventHandler : EventAction<Nothing>() {
        override fun action(event: KSLEvent<Nothing>) {
            incrementNumberOfEvents()
            if (!isDone) {
                generatorAction?.generate(this@EventGenerator) ?: generate()
                // get the time until next event
                val t: Double = myTimeBtwEventsRV.value
                // check if it is past end time
                if (t + time > endingTime) {
                    turnOffGenerator()
                }
                if (!isSuspended) {
                    if (!isDone) {// I'm not done generating, schedule the next event
                        schedule(t, priority = eventPriority)
                    }
                }
            }
        }
    }

    protected open fun generate() {
    }

    protected open fun endGeneration() {
    }

    companion object {
        /**
         * Determines the priority of the event generator's events The default is
         * DEFAULT_PRIORITY - 1 A lower number implies higher priority.
         */
        const val EVENT_PRIORITY: Int = KSLEvent.DEFAULT_PRIORITY - 1

        fun builder(parent: ModelElement): ActionStepIfc {
            return EventGeneratorBuilder(parent)
        }
    }
}