rootProject.name = "KSL"

include(":KSLCore")
include(":KSLApp")
include(":KSLExamples")
include(":KSLTestModels")
include(":KSLAppSwingCommon")
include(":KSLAppSwingSingle")
include(":KSLAppSwingScenario")
include(":KSLAppSwingExperiment")
include(":KSLAppSwingSimopt")
include(":KSLAppSwingDistribution")
include(":KSLAppSwingResults")
include(":KSLBundleTools")
include(":KSLTesting")
include(":KSLProjectTemplate")
