/*
 * This file is generated by jOOQ.
 */
package ksl.utilities.io.dbutil.ksldbjooq.tables.records


import ksl.utilities.io.dbutil.ksldbjooq.tables.AcrossRepView

import org.jooq.Field
import org.jooq.Record5
import org.jooq.Row5
import org.jooq.impl.TableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class AcrossRepViewRecord() : TableRecordImpl<AcrossRepViewRecord>(AcrossRepView.ACROSS_REP_VIEW), Record5<String?, String?, Double?, Double?, Double?> {

    open var expName: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var statName: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var statCount: Double?
        set(value): Unit = set(2, value)
        get(): Double? = get(2) as Double?

    open var average: Double?
        set(value): Unit = set(3, value)
        get(): Double? = get(3) as Double?

    open var stdDev: Double?
        set(value): Unit = set(4, value)
        get(): Double? = get(4) as Double?

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row5<String?, String?, Double?, Double?, Double?> = super.fieldsRow() as Row5<String?, String?, Double?, Double?, Double?>
    override fun valuesRow(): Row5<String?, String?, Double?, Double?, Double?> = super.valuesRow() as Row5<String?, String?, Double?, Double?, Double?>
    override fun field1(): Field<String?> = AcrossRepView.ACROSS_REP_VIEW.EXP_NAME
    override fun field2(): Field<String?> = AcrossRepView.ACROSS_REP_VIEW.STAT_NAME
    override fun field3(): Field<Double?> = AcrossRepView.ACROSS_REP_VIEW.STAT_COUNT
    override fun field4(): Field<Double?> = AcrossRepView.ACROSS_REP_VIEW.AVERAGE
    override fun field5(): Field<Double?> = AcrossRepView.ACROSS_REP_VIEW.STD_DEV
    override fun component1(): String? = expName
    override fun component2(): String? = statName
    override fun component3(): Double? = statCount
    override fun component4(): Double? = average
    override fun component5(): Double? = stdDev
    override fun value1(): String? = expName
    override fun value2(): String? = statName
    override fun value3(): Double? = statCount
    override fun value4(): Double? = average
    override fun value5(): Double? = stdDev

    override fun value1(value: String?): AcrossRepViewRecord {
        this.expName = value
        return this
    }

    override fun value2(value: String?): AcrossRepViewRecord {
        this.statName = value
        return this
    }

    override fun value3(value: Double?): AcrossRepViewRecord {
        this.statCount = value
        return this
    }

    override fun value4(value: Double?): AcrossRepViewRecord {
        this.average = value
        return this
    }

    override fun value5(value: Double?): AcrossRepViewRecord {
        this.stdDev = value
        return this
    }

    override fun values(value1: String?, value2: String?, value3: Double?, value4: Double?, value5: Double?): AcrossRepViewRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        return this
    }

    /**
     * Create a detached, initialised AcrossRepViewRecord
     */
    constructor(expName: String? = null, statName: String? = null, statCount: Double? = null, average: Double? = null, stdDev: Double? = null): this() {
        this.expName = expName
        this.statName = statName
        this.statCount = statCount
        this.average = average
        this.stdDev = stdDev
    }
}
