/*
 * This file is generated by jOOQ.
 */
package ksl.utilities.io.dbutil.ksldbjooq.tables.records


import ksl.utilities.io.dbutil.ksldbjooq.tables.WithinRepResponseView

import org.jooq.Field
import org.jooq.Record8
import org.jooq.Row8
import org.jooq.impl.TableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class WithinRepResponseViewRecord() : TableRecordImpl<WithinRepResponseViewRecord>(WithinRepResponseView.WITHIN_REP_RESPONSE_VIEW), Record8<String?, String?, Int?, Int?, Int?, String?, Int?, Double?> {

    open var expName: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var runName: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var numReps: Int?
        set(value): Unit = set(2, value)
        get(): Int? = get(2) as Int?

    open var startRepId: Int?
        set(value): Unit = set(3, value)
        get(): Int? = get(3) as Int?

    open var lastRepId: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    open var statName: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var repId: Int?
        set(value): Unit = set(6, value)
        get(): Int? = get(6) as Int?

    open var average: Double?
        set(value): Unit = set(7, value)
        get(): Double? = get(7) as Double?

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row8<String?, String?, Int?, Int?, Int?, String?, Int?, Double?> = super.fieldsRow() as Row8<String?, String?, Int?, Int?, Int?, String?, Int?, Double?>
    override fun valuesRow(): Row8<String?, String?, Int?, Int?, Int?, String?, Int?, Double?> = super.valuesRow() as Row8<String?, String?, Int?, Int?, Int?, String?, Int?, Double?>
    override fun field1(): Field<String?> = WithinRepResponseView.WITHIN_REP_RESPONSE_VIEW.EXP_NAME
    override fun field2(): Field<String?> = WithinRepResponseView.WITHIN_REP_RESPONSE_VIEW.RUN_NAME
    override fun field3(): Field<Int?> = WithinRepResponseView.WITHIN_REP_RESPONSE_VIEW.NUM_REPS
    override fun field4(): Field<Int?> = WithinRepResponseView.WITHIN_REP_RESPONSE_VIEW.START_REP_ID
    override fun field5(): Field<Int?> = WithinRepResponseView.WITHIN_REP_RESPONSE_VIEW.LAST_REP_ID
    override fun field6(): Field<String?> = WithinRepResponseView.WITHIN_REP_RESPONSE_VIEW.STAT_NAME
    override fun field7(): Field<Int?> = WithinRepResponseView.WITHIN_REP_RESPONSE_VIEW.REP_ID
    override fun field8(): Field<Double?> = WithinRepResponseView.WITHIN_REP_RESPONSE_VIEW.AVERAGE
    override fun component1(): String? = expName
    override fun component2(): String? = runName
    override fun component3(): Int? = numReps
    override fun component4(): Int? = startRepId
    override fun component5(): Int? = lastRepId
    override fun component6(): String? = statName
    override fun component7(): Int? = repId
    override fun component8(): Double? = average
    override fun value1(): String? = expName
    override fun value2(): String? = runName
    override fun value3(): Int? = numReps
    override fun value4(): Int? = startRepId
    override fun value5(): Int? = lastRepId
    override fun value6(): String? = statName
    override fun value7(): Int? = repId
    override fun value8(): Double? = average

    override fun value1(value: String?): WithinRepResponseViewRecord {
        this.expName = value
        return this
    }

    override fun value2(value: String?): WithinRepResponseViewRecord {
        this.runName = value
        return this
    }

    override fun value3(value: Int?): WithinRepResponseViewRecord {
        this.numReps = value
        return this
    }

    override fun value4(value: Int?): WithinRepResponseViewRecord {
        this.startRepId = value
        return this
    }

    override fun value5(value: Int?): WithinRepResponseViewRecord {
        this.lastRepId = value
        return this
    }

    override fun value6(value: String?): WithinRepResponseViewRecord {
        this.statName = value
        return this
    }

    override fun value7(value: Int?): WithinRepResponseViewRecord {
        this.repId = value
        return this
    }

    override fun value8(value: Double?): WithinRepResponseViewRecord {
        this.average = value
        return this
    }

    override fun values(value1: String?, value2: String?, value3: Int?, value4: Int?, value5: Int?, value6: String?, value7: Int?, value8: Double?): WithinRepResponseViewRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        return this
    }

    /**
     * Create a detached, initialised WithinRepResponseViewRecord
     */
    constructor(expName: String? = null, runName: String? = null, numReps: Int? = null, startRepId: Int? = null, lastRepId: Int? = null, statName: String? = null, repId: Int? = null, average: Double? = null): this() {
        this.expName = expName
        this.runName = runName
        this.numReps = numReps
        this.startRepId = startRepId
        this.lastRepId = lastRepId
        this.statName = statName
        this.repId = repId
        this.average = average
    }
}
