/*
 * This file is generated by jOOQ.
 */
package ksl.utilities.io.dbutil.ksldbjooq.keys


import ksl.utilities.io.dbutil.ksldbjooq.tables.AcrossRepStat
import ksl.utilities.io.dbutil.ksldbjooq.tables.BatchStat
import ksl.utilities.io.dbutil.ksldbjooq.tables.Control
import ksl.utilities.io.dbutil.ksldbjooq.tables.Experiment
import ksl.utilities.io.dbutil.ksldbjooq.tables.ModelElement
import ksl.utilities.io.dbutil.ksldbjooq.tables.RvParameter
import ksl.utilities.io.dbutil.ksldbjooq.tables.SimulationRun
import ksl.utilities.io.dbutil.ksldbjooq.tables.WithinRepCounterStat
import ksl.utilities.io.dbutil.ksldbjooq.tables.WithinRepStat
import ksl.utilities.io.dbutil.ksldbjooq.tables.records.AcrossRepStatRecord
import ksl.utilities.io.dbutil.ksldbjooq.tables.records.BatchStatRecord
import ksl.utilities.io.dbutil.ksldbjooq.tables.records.ControlRecord
import ksl.utilities.io.dbutil.ksldbjooq.tables.records.ExperimentRecord
import ksl.utilities.io.dbutil.ksldbjooq.tables.records.ModelElementRecord
import ksl.utilities.io.dbutil.ksldbjooq.tables.records.RvParameterRecord
import ksl.utilities.io.dbutil.ksldbjooq.tables.records.SimulationRunRecord
import ksl.utilities.io.dbutil.ksldbjooq.tables.records.WithinRepCounterStatRecord
import ksl.utilities.io.dbutil.ksldbjooq.tables.records.WithinRepStatRecord

import org.jooq.ForeignKey
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val `SQL0000000106-06B1817D-0186-32BA-7CC1-00000B26C650`: UniqueKey<AcrossRepStatRecord> = Internal.createUniqueKey(AcrossRepStat.ACROSS_REP_STAT, DSL.name("SQL0000000106-06b1817d-0186-32ba-7cc1-00000b26c650"), arrayOf(AcrossRepStat.ACROSS_REP_STAT.ID), true)
val `SQL0000000116-F13C81AC-0186-32BA-7CC1-00000B26C650`: UniqueKey<BatchStatRecord> = Internal.createUniqueKey(BatchStat.BATCH_STAT, DSL.name("SQL0000000116-f13c81ac-0186-32ba-7cc1-00000b26c650"), arrayOf(BatchStat.BATCH_STAT.ID), true)
val `SQL0000000095-A9D80140-0186-32BA-7CC1-00000B26C650`: UniqueKey<ControlRecord> = Internal.createUniqueKey(Control.CONTROL, DSL.name("SQL0000000095-a9d80140-0186-32ba-7cc1-00000b26c650"), arrayOf(Control.CONTROL.CONTROL_ID), true)
val EXP_NAME_UNIQUE: UniqueKey<ExperimentRecord> = Internal.createUniqueKey(Experiment.EXPERIMENT, DSL.name("EXP_NAME_UNIQUE"), arrayOf(Experiment.EXPERIMENT.EXP_NAME), true)
val `SQL0000000081-7FA040FF-0186-32BA-7CC1-00000B26C650`: UniqueKey<ExperimentRecord> = Internal.createUniqueKey(Experiment.EXPERIMENT, DSL.name("SQL0000000081-7fa040ff-0186-32ba-7cc1-00000b26c650"), arrayOf(Experiment.EXPERIMENT.EXP_ID), true)
val ME_NAME_UNIQUE: UniqueKey<ModelElementRecord> = Internal.createUniqueKey(ModelElement.MODEL_ELEMENT, DSL.name("ME_NAME_UNIQUE"), arrayOf(ModelElement.MODEL_ELEMENT.EXP_ID_FK, ModelElement.MODEL_ELEMENT.ELEMENT_NAME), true)
val ME_PRIM_KY: UniqueKey<ModelElementRecord> = Internal.createUniqueKey(ModelElement.MODEL_ELEMENT, DSL.name("ME_PRIM_KY"), arrayOf(ModelElement.MODEL_ELEMENT.EXP_ID_FK, ModelElement.MODEL_ELEMENT.ELEMENT_ID), true)
val `SQL0000000098-3F9E4152-0186-32BA-7CC1-00000B26C650`: UniqueKey<RvParameterRecord> = Internal.createUniqueKey(RvParameter.RV_PARAMETER, DSL.name("SQL0000000098-3f9e4152-0186-32ba-7cc1-00000b26c650"), arrayOf(RvParameter.RV_PARAMETER.RV_PARAM_ID), true)
val `SQL0000000084-CB76C10E-0186-32BA-7CC1-00000B26C650`: UniqueKey<SimulationRunRecord> = Internal.createUniqueKey(SimulationRun.SIMULATION_RUN, DSL.name("SQL0000000084-cb76c10e-0186-32ba-7cc1-00000b26c650"), arrayOf(SimulationRun.SIMULATION_RUN.RUN_ID), true)
val SR_NAME_EXP_UNIQUE: UniqueKey<SimulationRunRecord> = Internal.createUniqueKey(SimulationRun.SIMULATION_RUN, DSL.name("SR_NAME_EXP_UNIQUE"), arrayOf(SimulationRun.SIMULATION_RUN.EXP_ID_FK, SimulationRun.SIMULATION_RUN.RUN_NAME), true)
val `SQL0000000112-8FE48195-0186-32BA-7CC1-00000B26C650`: UniqueKey<WithinRepCounterStatRecord> = Internal.createUniqueKey(WithinRepCounterStat.WITHIN_REP_COUNTER_STAT, DSL.name("SQL0000000112-8fe48195-0186-32ba-7cc1-00000b26c650"), arrayOf(WithinRepCounterStat.WITHIN_REP_COUNTER_STAT.ID), true)
val WRCS_UNIQUE_ELEMENT_SIMRUN_REPNUM: UniqueKey<WithinRepCounterStatRecord> = Internal.createUniqueKey(WithinRepCounterStat.WITHIN_REP_COUNTER_STAT, DSL.name("WRCS_UNIQUE_ELEMENT_SIMRUN_REPNUM"), arrayOf(WithinRepCounterStat.WITHIN_REP_COUNTER_STAT.ELEMENT_ID_FK, WithinRepCounterStat.WITHIN_REP_COUNTER_STAT.SIM_RUN_ID_FK, WithinRepCounterStat.WITHIN_REP_COUNTER_STAT.REP_ID), true)
val `SQL0000000101-15B58164-0186-32BA-7CC1-00000B26C650`: UniqueKey<WithinRepStatRecord> = Internal.createUniqueKey(WithinRepStat.WITHIN_REP_STAT, DSL.name("SQL0000000101-15b58164-0186-32ba-7cc1-00000b26c650"), arrayOf(WithinRepStat.WITHIN_REP_STAT.ID), true)
val WRS_UNIQUE_ELEMENT_SIMRUN_REPNUM: UniqueKey<WithinRepStatRecord> = Internal.createUniqueKey(WithinRepStat.WITHIN_REP_STAT, DSL.name("WRS_UNIQUE_ELEMENT_SIMRUN_REPNUM"), arrayOf(WithinRepStat.WITHIN_REP_STAT.ELEMENT_ID_FK, WithinRepStat.WITHIN_REP_STAT.SIM_RUN_ID_FK, WithinRepStat.WITHIN_REP_STAT.REP_ID), true)

// -------------------------------------------------------------------------
// FOREIGN KEY definitions
// -------------------------------------------------------------------------

val ARS_SIMRUN_FK: ForeignKey<AcrossRepStatRecord, SimulationRunRecord> = Internal.createForeignKey(AcrossRepStat.ACROSS_REP_STAT, DSL.name("ARS_SIMRUN_FK"), arrayOf(AcrossRepStat.ACROSS_REP_STAT.SIM_RUN_ID_FK), ksl.utilities.io.dbutil.ksldbjooq.keys.`SQL0000000084-CB76C10E-0186-32BA-7CC1-00000B26C650`, arrayOf(SimulationRun.SIMULATION_RUN.RUN_ID), true)
val BS_SIMRUN_FK: ForeignKey<BatchStatRecord, SimulationRunRecord> = Internal.createForeignKey(BatchStat.BATCH_STAT, DSL.name("BS_SIMRUN_FK"), arrayOf(BatchStat.BATCH_STAT.SIM_RUN_ID_FK), ksl.utilities.io.dbutil.ksldbjooq.keys.`SQL0000000084-CB76C10E-0186-32BA-7CC1-00000B26C650`, arrayOf(SimulationRun.SIMULATION_RUN.RUN_ID), true)
val CONTROL_EXP_ID_FK: ForeignKey<ControlRecord, ExperimentRecord> = Internal.createForeignKey(Control.CONTROL, DSL.name("CONTROL_EXP_ID_FK"), arrayOf(Control.CONTROL.EXP_ID_FK), ksl.utilities.io.dbutil.ksldbjooq.keys.`SQL0000000081-7FA040FF-0186-32BA-7CC1-00000B26C650`, arrayOf(Experiment.EXPERIMENT.EXP_ID), true)
val CTL_MODEL_ELEMENT_FK: ForeignKey<ControlRecord, ModelElementRecord> = Internal.createForeignKey(Control.CONTROL, DSL.name("CTL_MODEL_ELEMENT_FK"), arrayOf(Control.CONTROL.EXP_ID_FK, Control.CONTROL.ELEMENT_ID_FK), ksl.utilities.io.dbutil.ksldbjooq.keys.ME_PRIM_KY, arrayOf(ModelElement.MODEL_ELEMENT.EXP_ID_FK, ModelElement.MODEL_ELEMENT.ELEMENT_ID), true)
val ME_EXP_ID_FK: ForeignKey<ModelElementRecord, ExperimentRecord> = Internal.createForeignKey(ModelElement.MODEL_ELEMENT, DSL.name("ME_EXP_ID_FK"), arrayOf(ModelElement.MODEL_ELEMENT.EXP_ID_FK), ksl.utilities.io.dbutil.ksldbjooq.keys.`SQL0000000081-7FA040FF-0186-32BA-7CC1-00000B26C650`, arrayOf(Experiment.EXPERIMENT.EXP_ID), true)
val RV_PARAM_EXP_ID_FK: ForeignKey<RvParameterRecord, ExperimentRecord> = Internal.createForeignKey(RvParameter.RV_PARAMETER, DSL.name("RV_PARAM_EXP_ID_FK"), arrayOf(RvParameter.RV_PARAMETER.EXP_ID_FK), ksl.utilities.io.dbutil.ksldbjooq.keys.`SQL0000000081-7FA040FF-0186-32BA-7CC1-00000B26C650`, arrayOf(Experiment.EXPERIMENT.EXP_ID), true)
val RV_PARAM_MODEL_ELEMENT_FK: ForeignKey<RvParameterRecord, ModelElementRecord> = Internal.createForeignKey(RvParameter.RV_PARAMETER, DSL.name("RV_PARAM_MODEL_ELEMENT_FK"), arrayOf(RvParameter.RV_PARAMETER.EXP_ID_FK, RvParameter.RV_PARAMETER.ELEMENT_ID_FK), ksl.utilities.io.dbutil.ksldbjooq.keys.ME_PRIM_KY, arrayOf(ModelElement.MODEL_ELEMENT.EXP_ID_FK, ModelElement.MODEL_ELEMENT.ELEMENT_ID), true)
val SR_EXP_ID_FK: ForeignKey<SimulationRunRecord, ExperimentRecord> = Internal.createForeignKey(SimulationRun.SIMULATION_RUN, DSL.name("SR_EXP_ID_FK"), arrayOf(SimulationRun.SIMULATION_RUN.EXP_ID_FK), ksl.utilities.io.dbutil.ksldbjooq.keys.`SQL0000000081-7FA040FF-0186-32BA-7CC1-00000B26C650`, arrayOf(Experiment.EXPERIMENT.EXP_ID), true)
val WRCS_SIMRUN_FK: ForeignKey<WithinRepCounterStatRecord, SimulationRunRecord> = Internal.createForeignKey(WithinRepCounterStat.WITHIN_REP_COUNTER_STAT, DSL.name("WRCS_SIMRUN_FK"), arrayOf(WithinRepCounterStat.WITHIN_REP_COUNTER_STAT.SIM_RUN_ID_FK), ksl.utilities.io.dbutil.ksldbjooq.keys.`SQL0000000084-CB76C10E-0186-32BA-7CC1-00000B26C650`, arrayOf(SimulationRun.SIMULATION_RUN.RUN_ID), true)
val WRS_SIMRUN_FK: ForeignKey<WithinRepStatRecord, SimulationRunRecord> = Internal.createForeignKey(WithinRepStat.WITHIN_REP_STAT, DSL.name("WRS_SIMRUN_FK"), arrayOf(WithinRepStat.WITHIN_REP_STAT.SIM_RUN_ID_FK), ksl.utilities.io.dbutil.ksldbjooq.keys.`SQL0000000084-CB76C10E-0186-32BA-7CC1-00000B26C650`, arrayOf(SimulationRun.SIMULATION_RUN.RUN_ID), true)
