title = "ActiveFleetShop"
baseTimeUnit = null
width = 62.64
height = 80.64
background = [  ]
paths = [  ]
queues = [  ]
resources = [  ]
stations = [  ]
bars = [  ]
plots = [  ]
clocks = [  ]
spaces = [  ]
values = [  ]
agentStateColors = {  }
summaries = [  ]
histograms = [  ]
storages = [  ]
movableResources = [  ]
processColors = {  }
conveyors = [  ]
labels = [  ]
spaceGeometry = [  ]

[[objectClasses]]
typeName = "Part"
shape = "CIRCLE"
color = "#1f77b4"
size = 10.0
imageRef = null
label = null

[[objectClasses]]
typeName = "Source"
shape = "CIRCLE"
color = "#ff7f0e"
size = 10.0
imageRef = null
label = null

[[locations]]
locationName = "EntryStation"
label = "EntryStation"

[locations.position]
x = 0.0
y = 72.0
z = 0.0

[[locations]]
locationName = "ExitStation"
label = "ExitStation"

[locations.position]
x = 0.0
y = -36.0
z = 0.0

[[locations]]
locationName = "CartDepot"
label = "CartDepot"

[locations.position]
x = 54.0
y = 72.0
z = 0.0

[[guidedPaths]]
spaceName = "Agv:Space"
scale = 1.0
floorOffsetPerZ = null
linkColor = "#7f7f7f"
linkWidth = 2.0
showZones = true
showIntersections = true
closureColor = "#d62728"
label = null

[guidedPaths.offset]
x = 0.0
y = 0.0
z = 0.0

[[guidedTransporters]]
name = "Cart:Body"
shape = "SQUARE"
size = 6.75
color = "#1f77b4"
loadedColor = null
blockedColor = null
haltedColor = null
imageRef = null
label = null