title = "MultiFloorHospital"
baseTimeUnit = null
width = 131.10350819325745
height = 57.38947258483123
background = [  ]
paths = [  ]
queues = [  ]
resources = [  ]
stations = [  ]
bars = [  ]
plots = [  ]
clocks = [  ]
spaces = [  ]
values = [  ]
agentStateColors = {  }
summaries = [  ]
histograms = [  ]
storages = [  ]
movableResources = [  ]
processColors = {  }
conveyors = [  ]
labels = [  ]
spaceGeometry = [  ]

[[objectClasses]]
typeName = "Order"
shape = "CIRCLE"
color = "#1f77b4"
size = 10.0
imageRef = null
label = null

[[locations]]
locationName = "Lobby"
label = "Lobby"

[locations.position]
x = 0.0
y = 26.58980933132962
z = 0.0

[[locations]]
locationName = "WardA"
label = "WardA"

[locations.position]
x = 60.0
y = 26.58980933132962
z = 0.0

[[locations]]
locationName = "Pharmacy"
label = "Pharmacy"

[locations.position]
x = 60.0
y = 0.0
z = 0.0

[[locations]]
locationName = "Park1"
label = "Park1"

[locations.position]
x = 18.79385241571817
y = 33.43021219784299
z = 0.0

[[locations]]
locationName = "Park2"
label = "Park2"

[locations.position]
x = 15.32088886237956
y = 39.445561525060405
z = 0.0

[[locations]]
locationName = "Park3"
label = "Park3"

[locations.position]
x = 10.000000000000002
y = 43.91031740701839
z = 0.0

[[locations]]
locationName = "Park4"
label = "Park4"

[locations.position]
x = 3.4729635533386083
y = 46.28596439157378
z = 0.0

[[locations]]
locationName = "Park5"
label = "Park5"

[locations.position]
x = -3.472963553338606
y = 46.28596439157378
z = 0.0

[[locations]]
locationName = "Park6"
label = "Park6"

[locations.position]
x = -9.999999999999996
y = 43.9103174070184
z = 0.0

[[locations]]
locationName = "Park7"
label = "Park7"

[locations.position]
x = -15.320888862379558
y = 39.44556152506041
z = 0.0

[[locations]]
locationName = "Park8"
label = "Park8"

[locations.position]
x = -18.793852415718167
y = 33.430212197843
z = 0.0

[[guidedPaths]]
spaceName = "Agv:Space"
scale = 1.0
linkColor = "#7f7f7f"
linkWidth = 2.0
showZones = true
showIntersections = true
closureColor = "#d62728"
label = null

[guidedPaths.offset]
x = 0.0
y = 26.58980933132962
z = 0.0

[guidedPaths.floorOffsetPerZ]
x = 0.0
y = -0.3323726166416202
z = 0.0

[[guidedTransporters]]
name = "Porter1:Body"
shape = "SQUARE"
size = 2.892872774473361
color = "#1f77b4"
loadedColor = null
blockedColor = null
haltedColor = null
imageRef = null
label = null

[[guidedTransporters]]
name = "Porter2:Body"
shape = "SQUARE"
size = 2.892872774473361
color = "#1f77b4"
loadedColor = null
blockedColor = null
haltedColor = null
imageRef = null
label = null

[[guidedTransporters]]
name = "Porter3:Body"
shape = "SQUARE"
size = 2.892872774473361
color = "#1f77b4"
loadedColor = null
blockedColor = null
haltedColor = null
imageRef = null
label = null