/*
 * This file is generated by jOOQ.
 */
package ksl.utilities.io.dbutil.ksldbjooq.tables.references


import ksl.utilities.io.dbutil.ksldbjooq.tables.AcrossRepStat
import ksl.utilities.io.dbutil.ksldbjooq.tables.AcrossRepView
import ksl.utilities.io.dbutil.ksldbjooq.tables.BatchStat
import ksl.utilities.io.dbutil.ksldbjooq.tables.BatchStatView
import ksl.utilities.io.dbutil.ksldbjooq.tables.Control
import ksl.utilities.io.dbutil.ksldbjooq.tables.ExpStatRepView
import ksl.utilities.io.dbutil.ksldbjooq.tables.Experiment
import ksl.utilities.io.dbutil.ksldbjooq.tables.ModelElement
import ksl.utilities.io.dbutil.ksldbjooq.tables.PwDiffWithinRepView
import ksl.utilities.io.dbutil.ksldbjooq.tables.RvParameter
import ksl.utilities.io.dbutil.ksldbjooq.tables.SimulationRun
import ksl.utilities.io.dbutil.ksldbjooq.tables.WithinRepCounterStat
import ksl.utilities.io.dbutil.ksldbjooq.tables.WithinRepCounterView
import ksl.utilities.io.dbutil.ksldbjooq.tables.WithinRepResponseView
import ksl.utilities.io.dbutil.ksldbjooq.tables.WithinRepStat
import ksl.utilities.io.dbutil.ksldbjooq.tables.WithinRepView



/**
 * The table <code>KSL_DB.ACROSS_REP_STAT</code>.
 */
val ACROSS_REP_STAT: AcrossRepStat = AcrossRepStat.ACROSS_REP_STAT

/**
 * The table <code>KSL_DB.ACROSS_REP_VIEW</code>.
 */
val ACROSS_REP_VIEW: AcrossRepView = AcrossRepView.ACROSS_REP_VIEW

/**
 * The table <code>KSL_DB.BATCH_STAT</code>.
 */
val BATCH_STAT: BatchStat = BatchStat.BATCH_STAT

/**
 * The table <code>KSL_DB.BATCH_STAT_VIEW</code>.
 */
val BATCH_STAT_VIEW: BatchStatView = BatchStatView.BATCH_STAT_VIEW

/**
 * The table <code>KSL_DB.CONTROL</code>.
 */
val CONTROL: Control = Control.CONTROL

/**
 * The table <code>KSL_DB.EXP_STAT_REP_VIEW</code>.
 */
val EXP_STAT_REP_VIEW: ExpStatRepView = ExpStatRepView.EXP_STAT_REP_VIEW

/**
 * The table <code>KSL_DB.EXPERIMENT</code>.
 */
val EXPERIMENT: Experiment = Experiment.EXPERIMENT

/**
 * The table <code>KSL_DB.MODEL_ELEMENT</code>.
 */
val MODEL_ELEMENT: ModelElement = ModelElement.MODEL_ELEMENT

/**
 * The table <code>KSL_DB.PW_DIFF_WITHIN_REP_VIEW</code>.
 */
val PW_DIFF_WITHIN_REP_VIEW: PwDiffWithinRepView = PwDiffWithinRepView.PW_DIFF_WITHIN_REP_VIEW

/**
 * The table <code>KSL_DB.RV_PARAMETER</code>.
 */
val RV_PARAMETER: RvParameter = RvParameter.RV_PARAMETER

/**
 * The table <code>KSL_DB.SIMULATION_RUN</code>.
 */
val SIMULATION_RUN: SimulationRun = SimulationRun.SIMULATION_RUN

/**
 * The table <code>KSL_DB.WITHIN_REP_COUNTER_STAT</code>.
 */
val WITHIN_REP_COUNTER_STAT: WithinRepCounterStat = WithinRepCounterStat.WITHIN_REP_COUNTER_STAT

/**
 * The table <code>KSL_DB.WITHIN_REP_COUNTER_VIEW</code>.
 */
val WITHIN_REP_COUNTER_VIEW: WithinRepCounterView = WithinRepCounterView.WITHIN_REP_COUNTER_VIEW

/**
 * The table <code>KSL_DB.WITHIN_REP_RESPONSE_VIEW</code>.
 */
val WITHIN_REP_RESPONSE_VIEW: WithinRepResponseView = WithinRepResponseView.WITHIN_REP_RESPONSE_VIEW

/**
 * The table <code>KSL_DB.WITHIN_REP_STAT</code>.
 */
val WITHIN_REP_STAT: WithinRepStat = WithinRepStat.WITHIN_REP_STAT

/**
 * The table <code>KSL_DB.WITHIN_REP_VIEW</code>.
 */
val WITHIN_REP_VIEW: WithinRepView = WithinRepView.WITHIN_REP_VIEW
