/*
 *     The KSL provides a discrete-event simulation library for the Kotlin programming language.
 *     Copyright (C) 2023  Manuel D. Rossetti, rossetti@uark.edu
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package ksl.utilities.io.dbutil

/**
 * Writes a list of [SimulationSnapshot] objects produced by [InMemorySnapshotCollector]
 * into a [KSLDatabase] in a single sequential pass.
 *
 * The snapshots arrive with placeholder FK values (`exp_id = -1`, `run_id = -1`) set by
 * `SimulationLifeCycleBridge`.  This writer inserts the experiment and simulation-run records
 * first, reads back the auto-increment IDs generated by the database, then fixes all
 * downstream FK fields before inserting the remaining records.
 *
 * Expected snapshot order (produced by a clean run):
 * 1. Exactly one [SimulationSnapshot.ExperimentStarted]
 * 2. One [SimulationSnapshot.ReplicationCompleted] per replication
 * 3. Exactly one [SimulationSnapshot.ExperimentCompleted] **or** [SimulationSnapshot.ExperimentFailed]
 *
 * Snapshots are mutated in-place during FK remapping; the caller should not reuse the list.
 */
class SnapshotBatchWriter(private val db: KSLDatabase) {

    /**
     * Writes [snapshots] to [db].
     *
     * @throws IllegalArgumentException if [snapshots] contains no [SimulationSnapshot.ExperimentStarted].
     */
    fun write(snapshots: List<SimulationSnapshot>) {
        require(snapshots.isNotEmpty()) { "snapshots must not be empty" }

        val started = snapshots.filterIsInstance<SimulationSnapshot.ExperimentStarted>().firstOrNull()
            ?: throw IllegalArgumentException("snapshots contains no ExperimentStarted record")

        // Step 1 — insert experiment; exp_id is populated by the DB via setAutoIncField
        db.insertExperimentRecord(started.experiment)
        val realExpId = started.experiment.exp_id

        // Step 2 — fix exp_id_fk on run record, insert it; run_id populated by DB
        started.simulationRun.exp_id_fk = realExpId
        db.insertSimulationRunRecord(started.simulationRun)
        val realRunId = started.simulationRun.run_id

        // Step 3 — model elements, controls, rv parameters (all keyed to exp_id)
        started.modelElements.forEach { it.exp_id_fk = realExpId }
        if (started.modelElements.isNotEmpty()) {
            db.insertModelElementData(started.modelElements)
        }

        started.controls.forEach { it.exp_id_fk = realExpId }
        if (started.controls.isNotEmpty()) {
            db.insertControlData(started.controls)
        }

        started.rvParameters.forEach { it.exp_id_fk = realExpId }
        if (started.rvParameters.isNotEmpty()) {
            db.insertRvParameterData(started.rvParameters)
        }

        // Step 4 — per-replication records (keyed to run_id)
        for (rep in snapshots.filterIsInstance<SimulationSnapshot.ReplicationCompleted>()) {
            rep.withinRepStats.forEach { it.sim_run_id_fk = realRunId }
            if (rep.withinRepStats.isNotEmpty()) {
                db.insertWithinRepStatData(rep.withinRepStats)
            }

            rep.withinRepCounterStats.forEach { it.sim_run_id_fk = realRunId }
            if (rep.withinRepCounterStats.isNotEmpty()) {
                db.insertWithinRepCounterStatData(rep.withinRepCounterStats)
            }

            rep.batchStats.forEach { it.sim_run_id_fk = realRunId }
            if (rep.batchStats.isNotEmpty()) {
                db.insertBatchStatData(rep.batchStats)
            }
        }

        // Step 5 — finalize: experiment completed or failed
        val completed = snapshots.filterIsInstance<SimulationSnapshot.ExperimentCompleted>().firstOrNull()
        if (completed != null) {
            completed.simulationRun.run_id = realRunId
            completed.simulationRun.exp_id_fk = realExpId
            db.updateSimulationRunRecord(completed.simulationRun)

            completed.acrossRepStats.forEach { it.sim_run_id_fk = realRunId }
            if (completed.acrossRepStats.isNotEmpty()) {
                db.insertAcrossRepStatData(completed.acrossRepStats)
            }

            completed.histograms.forEach { it.sim_run_id_fk = realRunId }
            if (completed.histograms.isNotEmpty()) {
                db.insertHistogramData(completed.histograms)
            }

            completed.frequencies.forEach { it.sim_run_id_fk = realRunId }
            if (completed.frequencies.isNotEmpty()) {
                db.insertFrequencyData(completed.frequencies)
            }

            completed.timeSeries.forEach { it.sim_run_id_fk = realRunId }
            if (completed.timeSeries.isNotEmpty()) {
                db.insertTimeSeriesResponseData(completed.timeSeries)
            }
        }

        val failed = snapshots.filterIsInstance<SimulationSnapshot.ExperimentFailed>().firstOrNull()
        if (failed != null) {
            failed.partialSimulationRun.run_id = realRunId
            failed.partialSimulationRun.exp_id_fk = realExpId
            db.updateSimulationRunRecord(failed.partialSimulationRun)
        }
    }
}
