/*
 * This file is generated by jOOQ.
 */
package ksl.utilities.io.dbutil.ksldbjooq.indexes


import ksl.utilities.io.dbutil.ksldbjooq.tables.AcrossRepStat
import ksl.utilities.io.dbutil.ksldbjooq.tables.BatchStat
import ksl.utilities.io.dbutil.ksldbjooq.tables.WithinRepCounterStat
import ksl.utilities.io.dbutil.ksldbjooq.tables.WithinRepStat

import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val ARS_ME_FK_INDEX: Index = Internal.createIndex(DSL.name("ARS_ME_FK_INDEX"), AcrossRepStat.ACROSS_REP_STAT, arrayOf(AcrossRepStat.ACROSS_REP_STAT.SIM_RUN_ID_FK, AcrossRepStat.ACROSS_REP_STAT.ELEMENT_ID_FK), true)
val BS_ME_FK_INDEX: Index = Internal.createIndex(DSL.name("BS_ME_FK_INDEX"), BatchStat.BATCH_STAT, arrayOf(BatchStat.BATCH_STAT.SIM_RUN_ID_FK, BatchStat.BATCH_STAT.ELEMENT_ID_FK), false)
val WRCS_ME_FK_INDEX: Index = Internal.createIndex(DSL.name("WRCS_ME_FK_INDEX"), WithinRepCounterStat.WITHIN_REP_COUNTER_STAT, arrayOf(WithinRepCounterStat.WITHIN_REP_COUNTER_STAT.SIM_RUN_ID_FK, WithinRepCounterStat.WITHIN_REP_COUNTER_STAT.ELEMENT_ID_FK), false)
val WRS_ME_FK_INDEX: Index = Internal.createIndex(DSL.name("WRS_ME_FK_INDEX"), WithinRepStat.WITHIN_REP_STAT, arrayOf(WithinRepStat.WITHIN_REP_STAT.SIM_RUN_ID_FK, WithinRepStat.WITHIN_REP_STAT.ELEMENT_ID_FK), false)
