package ksl.modeling.supplychain

/**
 * Status codes attached to a demand when it is rejected, negotiated,
 * or otherwise routed through the demand-handling pipeline.
 *
 * Replaces the ten `public static final int` constants on
 * `sc.inventorylayer.Demand` in the legacy Java source, which were
 * generated by `JSL.getInstance().getNextEnumConstant()` — a
 * class-load-order-dependent global counter. See `docs/porting-plan.md`
 * §4.5 for the rationale.
 */
enum class DemandStatusCode {
    /** No status has been set for the demand. */
    NoStatus,

    /** The demand will be filled in full, immediately. */
    ImmediateFill,

    /** The demand will be backlogged. */
    WillBeBacklogged,

    /** The selected filler was unavailable to fill the demand. */
    FillerUnavailable,

    /** The demand's item type cannot be processed by the receiver. */
    ItemTypeMismatch,

    /**
     * A non-partial-fill demand was sent to a partial-filling receiver.
     * Legacy name: `NPFD_SENT_TO_PFR`.
     */
    NonPartialDemandToPartialFillingReceiver,

    /**
     * A non-backloggable demand was sent to a backlogging receiver and
     * could not be immediately filled.
     * Legacy name: `NBLD_SENT_TO_BLR_NIF`.
     */
    NonBackloggableDemandToBackloggingReceiverNotImmediateFill,

    /**
     * A non-backloggable demand was sent to a non-backlogging receiver
     * and could not be immediately filled.
     * Legacy name: `NBLD_SENT_TO_NBLR_NIF`.
     */
    NonBackloggableDemandToNonBackloggingReceiverNotImmediateFill,

    /**
     * A backloggable demand was sent to a non-backlogging receiver and
     * could not be immediately filled.
     * Legacy name: `BLD_SENT_TO_NBLR_NIF`.
     */
    BackloggableDemandToNonBackloggingReceiverNotImmediateFill,

    /** The order this demand was placed on was rejected. */
    OrderRejected,
}
