package ksl.modeling.supplychain

/**
 * Status codes attached to an order during negotiation and routing.
 *
 * Replaces the five `public static final int` constants on
 * `sc.inventorylayer.Order` in the legacy Java source, which were
 * generated by `JSL.getInstance().getNextEnumConstant()`. See
 * `docs/porting-plan.md` §4.5.
 */
enum class OrderStatusCode {
    /** No status has been set for the order. */
    NoStatus,

    /** At least one demand on this order was rejected. */
    DemandRejected,

    /** The order will be filled in full, immediately. */
    ImmediateFill,

    /** The order will be backlogged. */
    WillBeBacklogged,

    /** The selected filler was unavailable to fill the order. */
    FillerUnavailable,
}
