ALTER TABLE S ADD CONSTRAINT S_PK PRIMARY KEY (SNUM);
ALTER TABLE S ADD CONSTRAINT S_NAME_UNIQUE UNIQUE (SNAME);
ALTER TABLE P ADD CONSTRAINT P_PK PRIMARY KEY (PNUM);
ALTER TABLE P ADD CONSTRAINT PNAME_COLOR_CITY_UNIQUE UNIQUE (PNAME, COLOR, CITY);
ALTER TABLE SP ADD CONSTRAINT SP_PK PRIMARY KEY(SNUM_FK, PNUM_FK);
ALTER TABLE SP ADD CONSTRAINT SP_S_FK FOREIGN KEY (SNUM_FK) REFERENCES S (SNUM);
ALTER TABLE SP ADD CONSTRAINT SP_P_FK FOREIGN KEY (PNUM_FK) REFERENCES P (PNUM);