/*
 * This file is generated by jOOQ.
 */
package ksl.utilities.io.dbutil.ksldbjooq.tables


import kotlin.collections.List

import ksl.utilities.io.dbutil.ksldbjooq.KslDb
import ksl.utilities.io.dbutil.ksldbjooq.indexes.BS_ME_FK_INDEX
import ksl.utilities.io.dbutil.ksldbjooq.keys.BS_SIMRUN_FK
import ksl.utilities.io.dbutil.ksldbjooq.tables.records.BatchStatRecord

import org.jooq.Check
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class BatchStat(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, BatchStatRecord>?,
    aliased: Table<BatchStatRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<BatchStatRecord>(
    alias,
    KslDb.KSL_DB,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>KSL_DB.BATCH_STAT</code>
         */
        val BATCH_STAT: BatchStat = BatchStat()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<BatchStatRecord> = BatchStatRecord::class.java

    /**
     * The column <code>KSL_DB.BATCH_STAT.ID</code>.
     */
    val ID: TableField<BatchStatRecord, Int?> = createField(DSL.name("ID"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>KSL_DB.BATCH_STAT.ELEMENT_ID_FK</code>.
     */
    val ELEMENT_ID_FK: TableField<BatchStatRecord, Int?> = createField(DSL.name("ELEMENT_ID_FK"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>KSL_DB.BATCH_STAT.SIM_RUN_ID_FK</code>.
     */
    val SIM_RUN_ID_FK: TableField<BatchStatRecord, Int?> = createField(DSL.name("SIM_RUN_ID_FK"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>KSL_DB.BATCH_STAT.REP_ID</code>.
     */
    val REP_ID: TableField<BatchStatRecord, Int?> = createField(DSL.name("REP_ID"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>KSL_DB.BATCH_STAT.STAT_NAME</code>.
     */
    val STAT_NAME: TableField<BatchStatRecord, String?> = createField(DSL.name("STAT_NAME"), SQLDataType.VARCHAR(510), this, "")

    /**
     * The column <code>KSL_DB.BATCH_STAT.STAT_COUNT</code>.
     */
    val STAT_COUNT: TableField<BatchStatRecord, Double?> = createField(DSL.name("STAT_COUNT"), SQLDataType.DOUBLE, this, "")

    /**
     * The column <code>KSL_DB.BATCH_STAT.AVERAGE</code>.
     */
    val AVERAGE: TableField<BatchStatRecord, Double?> = createField(DSL.name("AVERAGE"), SQLDataType.DOUBLE, this, "")

    /**
     * The column <code>KSL_DB.BATCH_STAT.STD_DEV</code>.
     */
    val STD_DEV: TableField<BatchStatRecord, Double?> = createField(DSL.name("STD_DEV"), SQLDataType.DOUBLE, this, "")

    /**
     * The column <code>KSL_DB.BATCH_STAT.STD_ERR</code>.
     */
    val STD_ERR: TableField<BatchStatRecord, Double?> = createField(DSL.name("STD_ERR"), SQLDataType.DOUBLE, this, "")

    /**
     * The column <code>KSL_DB.BATCH_STAT.HALF_WIDTH</code>.
     */
    val HALF_WIDTH: TableField<BatchStatRecord, Double?> = createField(DSL.name("HALF_WIDTH"), SQLDataType.DOUBLE, this, "")

    /**
     * The column <code>KSL_DB.BATCH_STAT.CONF_LEVEL</code>.
     */
    val CONF_LEVEL: TableField<BatchStatRecord, Double?> = createField(DSL.name("CONF_LEVEL"), SQLDataType.DOUBLE, this, "")

    /**
     * The column <code>KSL_DB.BATCH_STAT.MINIMUM</code>.
     */
    val MINIMUM: TableField<BatchStatRecord, Double?> = createField(DSL.name("MINIMUM"), SQLDataType.DOUBLE, this, "")

    /**
     * The column <code>KSL_DB.BATCH_STAT.MAXIMUM</code>.
     */
    val MAXIMUM: TableField<BatchStatRecord, Double?> = createField(DSL.name("MAXIMUM"), SQLDataType.DOUBLE, this, "")

    /**
     * The column <code>KSL_DB.BATCH_STAT.SUM_OF_OBS</code>.
     */
    val SUM_OF_OBS: TableField<BatchStatRecord, Double?> = createField(DSL.name("SUM_OF_OBS"), SQLDataType.DOUBLE, this, "")

    /**
     * The column <code>KSL_DB.BATCH_STAT.DEV_SSQ</code>.
     */
    val DEV_SSQ: TableField<BatchStatRecord, Double?> = createField(DSL.name("DEV_SSQ"), SQLDataType.DOUBLE, this, "")

    /**
     * The column <code>KSL_DB.BATCH_STAT.LAST_VALUE</code>.
     */
    val LAST_VALUE: TableField<BatchStatRecord, Double?> = createField(DSL.name("LAST_VALUE"), SQLDataType.DOUBLE, this, "")

    /**
     * The column <code>KSL_DB.BATCH_STAT.KURTOSIS</code>.
     */
    val KURTOSIS: TableField<BatchStatRecord, Double?> = createField(DSL.name("KURTOSIS"), SQLDataType.DOUBLE, this, "")

    /**
     * The column <code>KSL_DB.BATCH_STAT.SKEWNESS</code>.
     */
    val SKEWNESS: TableField<BatchStatRecord, Double?> = createField(DSL.name("SKEWNESS"), SQLDataType.DOUBLE, this, "")

    /**
     * The column <code>KSL_DB.BATCH_STAT.LAG1_COV</code>.
     */
    val LAG1_COV: TableField<BatchStatRecord, Double?> = createField(DSL.name("LAG1_COV"), SQLDataType.DOUBLE, this, "")

    /**
     * The column <code>KSL_DB.BATCH_STAT.LAG1_CORR</code>.
     */
    val LAG1_CORR: TableField<BatchStatRecord, Double?> = createField(DSL.name("LAG1_CORR"), SQLDataType.DOUBLE, this, "")

    /**
     * The column <code>KSL_DB.BATCH_STAT.VON_NEUMANN_LAG1_STAT</code>.
     */
    val VON_NEUMANN_LAG1_STAT: TableField<BatchStatRecord, Double?> = createField(DSL.name("VON_NEUMANN_LAG1_STAT"), SQLDataType.DOUBLE, this, "")

    /**
     * The column <code>KSL_DB.BATCH_STAT.NUM_MISSING_OBS</code>.
     */
    val NUM_MISSING_OBS: TableField<BatchStatRecord, Double?> = createField(DSL.name("NUM_MISSING_OBS"), SQLDataType.DOUBLE, this, "")

    /**
     * The column <code>KSL_DB.BATCH_STAT.MIN_BATCH_SIZE</code>.
     */
    val MIN_BATCH_SIZE: TableField<BatchStatRecord, Double?> = createField(DSL.name("MIN_BATCH_SIZE"), SQLDataType.DOUBLE, this, "")

    /**
     * The column <code>KSL_DB.BATCH_STAT.MIN_NUM_BATCHES</code>.
     */
    val MIN_NUM_BATCHES: TableField<BatchStatRecord, Double?> = createField(DSL.name("MIN_NUM_BATCHES"), SQLDataType.DOUBLE, this, "")

    /**
     * The column <code>KSL_DB.BATCH_STAT.MAX_NUM_BATCHES_MULTIPLE</code>.
     */
    val MAX_NUM_BATCHES_MULTIPLE: TableField<BatchStatRecord, Double?> = createField(DSL.name("MAX_NUM_BATCHES_MULTIPLE"), SQLDataType.DOUBLE, this, "")

    /**
     * The column <code>KSL_DB.BATCH_STAT.MAX_NUM_BATCHES</code>.
     */
    val MAX_NUM_BATCHES: TableField<BatchStatRecord, Double?> = createField(DSL.name("MAX_NUM_BATCHES"), SQLDataType.DOUBLE, this, "")

    /**
     * The column <code>KSL_DB.BATCH_STAT.NUM_REBATCHES</code>.
     */
    val NUM_REBATCHES: TableField<BatchStatRecord, Double?> = createField(DSL.name("NUM_REBATCHES"), SQLDataType.DOUBLE, this, "")

    /**
     * The column <code>KSL_DB.BATCH_STAT.CURRENT_BATCH_SIZE</code>.
     */
    val CURRENT_BATCH_SIZE: TableField<BatchStatRecord, Double?> = createField(DSL.name("CURRENT_BATCH_SIZE"), SQLDataType.DOUBLE, this, "")

    /**
     * The column <code>KSL_DB.BATCH_STAT.AMT_UNBATCHED</code>.
     */
    val AMT_UNBATCHED: TableField<BatchStatRecord, Double?> = createField(DSL.name("AMT_UNBATCHED"), SQLDataType.DOUBLE, this, "")

    /**
     * The column <code>KSL_DB.BATCH_STAT.TOTAL_NUM_OBS</code>.
     */
    val TOTAL_NUM_OBS: TableField<BatchStatRecord, Double?> = createField(DSL.name("TOTAL_NUM_OBS"), SQLDataType.DOUBLE, this, "")

    private constructor(alias: Name, aliased: Table<BatchStatRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<BatchStatRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>KSL_DB.BATCH_STAT</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>KSL_DB.BATCH_STAT</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>KSL_DB.BATCH_STAT</code> table reference
     */
    constructor(): this(DSL.name("BATCH_STAT"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, BatchStatRecord>): this(Internal.createPathAlias(child, key), child, key, BATCH_STAT, null)
    override fun getSchema(): Schema? = if (aliased()) null else KslDb.KSL_DB
    override fun getIndexes(): List<Index> = listOf(BS_ME_FK_INDEX)
    override fun getIdentity(): Identity<BatchStatRecord, Int?> = super.getIdentity() as Identity<BatchStatRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<BatchStatRecord> = ksl.utilities.io.dbutil.ksldbjooq.keys.`SQL0000000116-F13C81AC-0186-32BA-7CC1-00000B26C650`
    override fun getReferences(): List<ForeignKey<BatchStatRecord, *>> = listOf(BS_SIMRUN_FK)

    private lateinit var _simulationRun: SimulationRun

    /**
     * Get the implicit join path to the <code>KSL_DB.SIMULATION_RUN</code>
     * table.
     */
    fun simulationRun(): SimulationRun {
        if (!this::_simulationRun.isInitialized)
            _simulationRun = SimulationRun(this, BS_SIMRUN_FK)

        return _simulationRun;
    }

    val simulationRun: SimulationRun
        get(): SimulationRun = simulationRun()
    override fun getChecks(): List<Check<BatchStatRecord>> = listOf(
        Internal.createCheck(this, DSL.name("SQL0000000117-19a781ad-0186-32ba-7cc1-00000b26c650"), "(REP_ID >= 1)", true),
        Internal.createCheck(this, DSL.name("SQL0000000118-0212c1ae-0186-32ba-7cc1-00000b26c650"), "(STAT_COUNT >= 0)", true),
        Internal.createCheck(this, DSL.name("SQL0000000119-ba7e41af-0186-32ba-7cc1-00000b26c650"), "(STD_DEV >= 0)", true),
        Internal.createCheck(this, DSL.name("SQL0000000120-52ea01b0-0186-32ba-7cc1-00000b26c650"), "(STD_ERR >= 0)", true),
        Internal.createCheck(this, DSL.name("SQL0000000121-db5601b1-0186-32ba-7cc1-00000b26c650"), "(HALF_WIDTH >= 0)", true)
    )
    override fun `as`(alias: String): BatchStat = BatchStat(DSL.name(alias), this)
    override fun `as`(alias: Name): BatchStat = BatchStat(alias, this)
    override fun `as`(alias: Table<*>): BatchStat = BatchStat(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): BatchStat = BatchStat(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): BatchStat = BatchStat(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): BatchStat = BatchStat(name.getQualifiedName(), null)
}
