/*
 * This file is generated by jOOQ.
 */
package ksl.utilities.io.dbutil.ksldbjooq.tables


import java.util.function.Function

import ksl.utilities.io.dbutil.ksldbjooq.KslDb
import ksl.utilities.io.dbutil.ksldbjooq.tables.records.BatchStatViewRecord

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row7
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class BatchStatView(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, BatchStatViewRecord>?,
    aliased: Table<BatchStatViewRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<BatchStatViewRecord>(
    alias,
    KslDb.KSL_DB,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.view("CREATE VIEW KSL_DB.BATCH_STAT_VIEW (EXP_NAME, RUN_NAME, REP_ID, STAT_NAME, STAT_COUNT, AVERAGE, STD_DEV) AS SELECT EXP_NAME, RUN_NAME, REP_ID, STAT_NAME, STAT_COUNT, AVERAGE, STD_DEV FROM KSL_DB.EXPERIMENT, KSL_DB.SIMULATION_RUN, KSL_DB.BATCH_STAT, KSL_DB.MODEL_ELEMENT WHERE KSL_DB.EXPERIMENT.EXP_ID = KSL_DB.SIMULATION_RUN.EXP_ID_FK AND KSL_DB.SIMULATION_RUN.RUN_ID = KSL_DB.BATCH_STAT.SIM_RUN_ID_FK AND KSL_DB.EXPERIMENT.EXP_ID = KSL_DB.MODEL_ELEMENT.EXP_ID_FK AND KSL_DB.MODEL_ELEMENT.ELEMENT_ID = KSL_DB.BATCH_STAT.ELEMENT_ID_FK AND KSL_DB.MODEL_ELEMENT.ELEMENT_NAME = KSL_DB.BATCH_STAT.STAT_NAME ORDER BY EXP_NAME, RUN_NAME, REP_ID, STAT_NAME")
) {
    companion object {

        /**
         * The reference instance of <code>KSL_DB.BATCH_STAT_VIEW</code>
         */
        val BATCH_STAT_VIEW: BatchStatView = BatchStatView()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<BatchStatViewRecord> = BatchStatViewRecord::class.java

    /**
     * The column <code>KSL_DB.BATCH_STAT_VIEW.EXP_NAME</code>.
     */
    val EXP_NAME: TableField<BatchStatViewRecord, String?> = createField(DSL.name("EXP_NAME"), SQLDataType.VARCHAR(510).nullable(false), this, "")

    /**
     * The column <code>KSL_DB.BATCH_STAT_VIEW.RUN_NAME</code>.
     */
    val RUN_NAME: TableField<BatchStatViewRecord, String?> = createField(DSL.name("RUN_NAME"), SQLDataType.VARCHAR(510).nullable(false), this, "")

    /**
     * The column <code>KSL_DB.BATCH_STAT_VIEW.REP_ID</code>.
     */
    val REP_ID: TableField<BatchStatViewRecord, Int?> = createField(DSL.name("REP_ID"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>KSL_DB.BATCH_STAT_VIEW.STAT_NAME</code>.
     */
    val STAT_NAME: TableField<BatchStatViewRecord, String?> = createField(DSL.name("STAT_NAME"), SQLDataType.VARCHAR(510), this, "")

    /**
     * The column <code>KSL_DB.BATCH_STAT_VIEW.STAT_COUNT</code>.
     */
    val STAT_COUNT: TableField<BatchStatViewRecord, Double?> = createField(DSL.name("STAT_COUNT"), SQLDataType.DOUBLE, this, "")

    /**
     * The column <code>KSL_DB.BATCH_STAT_VIEW.AVERAGE</code>.
     */
    val AVERAGE: TableField<BatchStatViewRecord, Double?> = createField(DSL.name("AVERAGE"), SQLDataType.DOUBLE, this, "")

    /**
     * The column <code>KSL_DB.BATCH_STAT_VIEW.STD_DEV</code>.
     */
    val STD_DEV: TableField<BatchStatViewRecord, Double?> = createField(DSL.name("STD_DEV"), SQLDataType.DOUBLE, this, "")

    private constructor(alias: Name, aliased: Table<BatchStatViewRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<BatchStatViewRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>KSL_DB.BATCH_STAT_VIEW</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>KSL_DB.BATCH_STAT_VIEW</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>KSL_DB.BATCH_STAT_VIEW</code> table reference
     */
    constructor(): this(DSL.name("BATCH_STAT_VIEW"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, BatchStatViewRecord>): this(Internal.createPathAlias(child, key), child, key, BATCH_STAT_VIEW, null)
    override fun getSchema(): Schema? = if (aliased()) null else KslDb.KSL_DB
    override fun `as`(alias: String): BatchStatView = BatchStatView(DSL.name(alias), this)
    override fun `as`(alias: Name): BatchStatView = BatchStatView(alias, this)
    override fun `as`(alias: Table<*>): BatchStatView = BatchStatView(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): BatchStatView = BatchStatView(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): BatchStatView = BatchStatView(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): BatchStatView = BatchStatView(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row7<String?, String?, Int?, String?, Double?, Double?, Double?> = super.fieldsRow() as Row7<String?, String?, Int?, String?, Double?, Double?, Double?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (String?, String?, Int?, String?, Double?, Double?, Double?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (String?, String?, Int?, String?, Double?, Double?, Double?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
