/*
 * This file is generated by jOOQ.
 */
package ksl.utilities.io.dbutil.ksldbjooq.tables


import java.util.function.Function

import kotlin.collections.List

import ksl.utilities.io.dbutil.ksldbjooq.KslDb
import ksl.utilities.io.dbutil.ksldbjooq.keys.CONTROL_EXP_ID_FK
import ksl.utilities.io.dbutil.ksldbjooq.keys.CTL_MODEL_ELEMENT_FK
import ksl.utilities.io.dbutil.ksldbjooq.tables.records.ControlRecord

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row10
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Control(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, ControlRecord>?,
    aliased: Table<ControlRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<ControlRecord>(
    alias,
    KslDb.KSL_DB,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>KSL_DB.CONTROL</code>
         */
        val CONTROL: Control = Control()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ControlRecord> = ControlRecord::class.java

    /**
     * The column <code>KSL_DB.CONTROL.CONTROL_ID</code>.
     */
    val CONTROL_ID: TableField<ControlRecord, Int?> = createField(DSL.name("CONTROL_ID"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>KSL_DB.CONTROL.EXP_ID_FK</code>.
     */
    val EXP_ID_FK: TableField<ControlRecord, Int?> = createField(DSL.name("EXP_ID_FK"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>KSL_DB.CONTROL.ELEMENT_ID_FK</code>.
     */
    val ELEMENT_ID_FK: TableField<ControlRecord, Int?> = createField(DSL.name("ELEMENT_ID_FK"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>KSL_DB.CONTROL.KEY_NAME</code>.
     */
    val KEY_NAME: TableField<ControlRecord, String?> = createField(DSL.name("KEY_NAME"), SQLDataType.VARCHAR(510).nullable(false), this, "")

    /**
     * The column <code>KSL_DB.CONTROL.CONTROL_VALUE</code>.
     */
    val CONTROL_VALUE: TableField<ControlRecord, Double?> = createField(DSL.name("CONTROL_VALUE"), SQLDataType.DOUBLE.nullable(false), this, "")

    /**
     * The column <code>KSL_DB.CONTROL.LOWER_BOUND</code>.
     */
    val LOWER_BOUND: TableField<ControlRecord, Double?> = createField(DSL.name("LOWER_BOUND"), SQLDataType.DOUBLE, this, "")

    /**
     * The column <code>KSL_DB.CONTROL.UPPER_BOUND</code>.
     */
    val UPPER_BOUND: TableField<ControlRecord, Double?> = createField(DSL.name("UPPER_BOUND"), SQLDataType.DOUBLE, this, "")

    /**
     * The column <code>KSL_DB.CONTROL.PROPERTY_NAME</code>.
     */
    val PROPERTY_NAME: TableField<ControlRecord, String?> = createField(DSL.name("PROPERTY_NAME"), SQLDataType.VARCHAR(510).nullable(false), this, "")

    /**
     * The column <code>KSL_DB.CONTROL.CONTROL_TYPE</code>.
     */
    val CONTROL_TYPE: TableField<ControlRecord, String?> = createField(DSL.name("CONTROL_TYPE"), SQLDataType.VARCHAR(510).nullable(false), this, "")

    /**
     * The column <code>KSL_DB.CONTROL.COMMENT</code>.
     */
    val COMMENT: TableField<ControlRecord, String?> = createField(DSL.name("COMMENT"), SQLDataType.VARCHAR(510), this, "")

    private constructor(alias: Name, aliased: Table<ControlRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<ControlRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>KSL_DB.CONTROL</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>KSL_DB.CONTROL</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>KSL_DB.CONTROL</code> table reference
     */
    constructor(): this(DSL.name("CONTROL"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, ControlRecord>): this(Internal.createPathAlias(child, key), child, key, CONTROL, null)
    override fun getSchema(): Schema? = if (aliased()) null else KslDb.KSL_DB
    override fun getIdentity(): Identity<ControlRecord, Int?> = super.getIdentity() as Identity<ControlRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<ControlRecord> = ksl.utilities.io.dbutil.ksldbjooq.keys.`SQL0000000095-A9D80140-0186-32BA-7CC1-00000B26C650`
    override fun getReferences(): List<ForeignKey<ControlRecord, *>> = listOf(CONTROL_EXP_ID_FK, CTL_MODEL_ELEMENT_FK)

    private lateinit var _experiment: Experiment
    private lateinit var _modelElement: ModelElement

    /**
     * Get the implicit join path to the <code>KSL_DB.EXPERIMENT</code> table.
     */
    fun experiment(): Experiment {
        if (!this::_experiment.isInitialized)
            _experiment = Experiment(this, CONTROL_EXP_ID_FK)

        return _experiment;
    }

    val experiment: Experiment
        get(): Experiment = experiment()

    /**
     * Get the implicit join path to the <code>KSL_DB.MODEL_ELEMENT</code>
     * table.
     */
    fun modelElement(): ModelElement {
        if (!this::_modelElement.isInitialized)
            _modelElement = ModelElement(this, CTL_MODEL_ELEMENT_FK)

        return _modelElement;
    }

    val modelElement: ModelElement
        get(): ModelElement = modelElement()
    override fun `as`(alias: String): Control = Control(DSL.name(alias), this)
    override fun `as`(alias: Name): Control = Control(alias, this)
    override fun `as`(alias: Table<*>): Control = Control(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Control = Control(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Control = Control(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Control = Control(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row10<Int?, Int?, Int?, String?, Double?, Double?, Double?, String?, String?, String?> = super.fieldsRow() as Row10<Int?, Int?, Int?, String?, Double?, Double?, Double?, String?, String?, String?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (Int?, Int?, Int?, String?, Double?, Double?, Double?, String?, String?, String?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (Int?, Int?, Int?, String?, Double?, Double?, Double?, String?, String?, String?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
