/*
 * This file is generated by jOOQ.
 */
package ksl.utilities.io.dbutil.ksldbjooq.tables


import java.util.function.Function

import ksl.utilities.io.dbutil.ksldbjooq.KslDb
import ksl.utilities.io.dbutil.ksldbjooq.tables.records.ExpStatRepViewRecord

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row4
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ExpStatRepView(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, ExpStatRepViewRecord>?,
    aliased: Table<ExpStatRepViewRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<ExpStatRepViewRecord>(
    alias,
    KslDb.KSL_DB,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.view("CREATE VIEW KSL_DB.EXP_STAT_REP_VIEW(EXP_NAME, STAT_NAME, REP_ID, REP_VALUE) AS SELECT EXP_NAME, STAT_NAME, REP_ID, REP_VALUE FROM KSL_DB.WITHIN_REP_VIEW ORDER BY EXP_NAME, STAT_NAME, REP_ID")
) {
    companion object {

        /**
         * The reference instance of <code>KSL_DB.EXP_STAT_REP_VIEW</code>
         */
        val EXP_STAT_REP_VIEW: ExpStatRepView = ExpStatRepView()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ExpStatRepViewRecord> = ExpStatRepViewRecord::class.java

    /**
     * The column <code>KSL_DB.EXP_STAT_REP_VIEW.EXP_NAME</code>.
     */
    val EXP_NAME: TableField<ExpStatRepViewRecord, String?> = createField(DSL.name("EXP_NAME"), SQLDataType.VARCHAR(510).nullable(false), this, "")

    /**
     * The column <code>KSL_DB.EXP_STAT_REP_VIEW.STAT_NAME</code>.
     */
    val STAT_NAME: TableField<ExpStatRepViewRecord, String?> = createField(DSL.name("STAT_NAME"), SQLDataType.VARCHAR(510), this, "")

    /**
     * The column <code>KSL_DB.EXP_STAT_REP_VIEW.REP_ID</code>.
     */
    val REP_ID: TableField<ExpStatRepViewRecord, Int?> = createField(DSL.name("REP_ID"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>KSL_DB.EXP_STAT_REP_VIEW.REP_VALUE</code>.
     */
    val REP_VALUE: TableField<ExpStatRepViewRecord, Double?> = createField(DSL.name("REP_VALUE"), SQLDataType.DOUBLE, this, "")

    private constructor(alias: Name, aliased: Table<ExpStatRepViewRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<ExpStatRepViewRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>KSL_DB.EXP_STAT_REP_VIEW</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>KSL_DB.EXP_STAT_REP_VIEW</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>KSL_DB.EXP_STAT_REP_VIEW</code> table reference
     */
    constructor(): this(DSL.name("EXP_STAT_REP_VIEW"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, ExpStatRepViewRecord>): this(Internal.createPathAlias(child, key), child, key, EXP_STAT_REP_VIEW, null)
    override fun getSchema(): Schema? = if (aliased()) null else KslDb.KSL_DB
    override fun `as`(alias: String): ExpStatRepView = ExpStatRepView(DSL.name(alias), this)
    override fun `as`(alias: Name): ExpStatRepView = ExpStatRepView(alias, this)
    override fun `as`(alias: Table<*>): ExpStatRepView = ExpStatRepView(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): ExpStatRepView = ExpStatRepView(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): ExpStatRepView = ExpStatRepView(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): ExpStatRepView = ExpStatRepView(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row4<String?, String?, Int?, Double?> = super.fieldsRow() as Row4<String?, String?, Int?, Double?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (String?, String?, Int?, Double?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (String?, String?, Int?, Double?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
