/*
 * This file is generated by jOOQ.
 */
package ksl.utilities.io.dbutil.ksldbjooq.tables


import java.util.function.Function

import kotlin.collections.List

import ksl.utilities.io.dbutil.ksldbjooq.KslDb
import ksl.utilities.io.dbutil.ksldbjooq.indexes.WRS_ME_FK_INDEX
import ksl.utilities.io.dbutil.ksldbjooq.keys.WRS_SIMRUN_FK
import ksl.utilities.io.dbutil.ksldbjooq.keys.WRS_UNIQUE_ELEMENT_SIMRUN_REPNUM
import ksl.utilities.io.dbutil.ksldbjooq.tables.records.WithinRepStatRecord

import org.jooq.Check
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row14
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class WithinRepStat(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, WithinRepStatRecord>?,
    aliased: Table<WithinRepStatRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<WithinRepStatRecord>(
    alias,
    KslDb.KSL_DB,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>KSL_DB.WITHIN_REP_STAT</code>
         */
        val WITHIN_REP_STAT: WithinRepStat = WithinRepStat()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<WithinRepStatRecord> = WithinRepStatRecord::class.java

    /**
     * The column <code>KSL_DB.WITHIN_REP_STAT.ID</code>.
     */
    val ID: TableField<WithinRepStatRecord, Int?> = createField(DSL.name("ID"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>KSL_DB.WITHIN_REP_STAT.ELEMENT_ID_FK</code>.
     */
    val ELEMENT_ID_FK: TableField<WithinRepStatRecord, Int?> = createField(DSL.name("ELEMENT_ID_FK"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>KSL_DB.WITHIN_REP_STAT.SIM_RUN_ID_FK</code>.
     */
    val SIM_RUN_ID_FK: TableField<WithinRepStatRecord, Int?> = createField(DSL.name("SIM_RUN_ID_FK"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>KSL_DB.WITHIN_REP_STAT.REP_ID</code>.
     */
    val REP_ID: TableField<WithinRepStatRecord, Int?> = createField(DSL.name("REP_ID"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>KSL_DB.WITHIN_REP_STAT.STAT_NAME</code>.
     */
    val STAT_NAME: TableField<WithinRepStatRecord, String?> = createField(DSL.name("STAT_NAME"), SQLDataType.VARCHAR(510), this, "")

    /**
     * The column <code>KSL_DB.WITHIN_REP_STAT.STAT_COUNT</code>.
     */
    val STAT_COUNT: TableField<WithinRepStatRecord, Double?> = createField(DSL.name("STAT_COUNT"), SQLDataType.DOUBLE, this, "")

    /**
     * The column <code>KSL_DB.WITHIN_REP_STAT.AVERAGE</code>.
     */
    val AVERAGE: TableField<WithinRepStatRecord, Double?> = createField(DSL.name("AVERAGE"), SQLDataType.DOUBLE, this, "")

    /**
     * The column <code>KSL_DB.WITHIN_REP_STAT.MINIMUM</code>.
     */
    val MINIMUM: TableField<WithinRepStatRecord, Double?> = createField(DSL.name("MINIMUM"), SQLDataType.DOUBLE, this, "")

    /**
     * The column <code>KSL_DB.WITHIN_REP_STAT.MAXIMUM</code>.
     */
    val MAXIMUM: TableField<WithinRepStatRecord, Double?> = createField(DSL.name("MAXIMUM"), SQLDataType.DOUBLE, this, "")

    /**
     * The column <code>KSL_DB.WITHIN_REP_STAT.WEIGHTED_SUM</code>.
     */
    val WEIGHTED_SUM: TableField<WithinRepStatRecord, Double?> = createField(DSL.name("WEIGHTED_SUM"), SQLDataType.DOUBLE, this, "")

    /**
     * The column <code>KSL_DB.WITHIN_REP_STAT.SUM_OF_WEIGHTS</code>.
     */
    val SUM_OF_WEIGHTS: TableField<WithinRepStatRecord, Double?> = createField(DSL.name("SUM_OF_WEIGHTS"), SQLDataType.DOUBLE, this, "")

    /**
     * The column <code>KSL_DB.WITHIN_REP_STAT.WEIGHTED_SSQ</code>.
     */
    val WEIGHTED_SSQ: TableField<WithinRepStatRecord, Double?> = createField(DSL.name("WEIGHTED_SSQ"), SQLDataType.DOUBLE, this, "")

    /**
     * The column <code>KSL_DB.WITHIN_REP_STAT.LAST_VALUE</code>.
     */
    val LAST_VALUE: TableField<WithinRepStatRecord, Double?> = createField(DSL.name("LAST_VALUE"), SQLDataType.DOUBLE, this, "")

    /**
     * The column <code>KSL_DB.WITHIN_REP_STAT.LAST_WEIGHT</code>.
     */
    val LAST_WEIGHT: TableField<WithinRepStatRecord, Double?> = createField(DSL.name("LAST_WEIGHT"), SQLDataType.DOUBLE, this, "")

    private constructor(alias: Name, aliased: Table<WithinRepStatRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<WithinRepStatRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>KSL_DB.WITHIN_REP_STAT</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>KSL_DB.WITHIN_REP_STAT</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>KSL_DB.WITHIN_REP_STAT</code> table reference
     */
    constructor(): this(DSL.name("WITHIN_REP_STAT"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, WithinRepStatRecord>): this(Internal.createPathAlias(child, key), child, key, WITHIN_REP_STAT, null)
    override fun getSchema(): Schema? = if (aliased()) null else KslDb.KSL_DB
    override fun getIndexes(): List<Index> = listOf(WRS_ME_FK_INDEX)
    override fun getIdentity(): Identity<WithinRepStatRecord, Int?> = super.getIdentity() as Identity<WithinRepStatRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<WithinRepStatRecord> = ksl.utilities.io.dbutil.ksldbjooq.keys.`SQL0000000101-15B58164-0186-32BA-7CC1-00000B26C650`
    override fun getUniqueKeys(): List<UniqueKey<WithinRepStatRecord>> = listOf(WRS_UNIQUE_ELEMENT_SIMRUN_REPNUM)
    override fun getReferences(): List<ForeignKey<WithinRepStatRecord, *>> = listOf(WRS_SIMRUN_FK)

    private lateinit var _simulationRun: SimulationRun

    /**
     * Get the implicit join path to the <code>KSL_DB.SIMULATION_RUN</code>
     * table.
     */
    fun simulationRun(): SimulationRun {
        if (!this::_simulationRun.isInitialized)
            _simulationRun = SimulationRun(this, WRS_SIMRUN_FK)

        return _simulationRun;
    }

    val simulationRun: SimulationRun
        get(): SimulationRun = simulationRun()
    override fun getChecks(): List<Check<WithinRepStatRecord>> = listOf(
        Internal.createCheck(this, DSL.name("SQL0000000102-7e0e8165-0186-32ba-7cc1-00000b26c650"), "(REP_ID >= 1)", true),
        Internal.createCheck(this, DSL.name("SQL0000000103-2667c166-0186-32ba-7cc1-00000b26c650"), "(STAT_COUNT >= 0)", true)
    )
    override fun `as`(alias: String): WithinRepStat = WithinRepStat(DSL.name(alias), this)
    override fun `as`(alias: Name): WithinRepStat = WithinRepStat(alias, this)
    override fun `as`(alias: Table<*>): WithinRepStat = WithinRepStat(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): WithinRepStat = WithinRepStat(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): WithinRepStat = WithinRepStat(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): WithinRepStat = WithinRepStat(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row14 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row14<Int?, Int?, Int?, Int?, String?, Double?, Double?, Double?, Double?, Double?, Double?, Double?, Double?, Double?> = super.fieldsRow() as Row14<Int?, Int?, Int?, Int?, String?, Double?, Double?, Double?, Double?, Double?, Double?, Double?, Double?, Double?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (Int?, Int?, Int?, Int?, String?, Double?, Double?, Double?, Double?, Double?, Double?, Double?, Double?, Double?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (Int?, Int?, Int?, Int?, String?, Double?, Double?, Double?, Double?, Double?, Double?, Double?, Double?, Double?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
