/*
 * This file is generated by jOOQ.
 */
package ksl.utilities.io.dbutil.ksldbjooq.tables


import java.util.function.Function

import ksl.utilities.io.dbutil.ksldbjooq.KslDb
import ksl.utilities.io.dbutil.ksldbjooq.tables.records.WithinRepViewRecord

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row8
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class WithinRepView(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, WithinRepViewRecord>?,
    aliased: Table<WithinRepViewRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<WithinRepViewRecord>(
    alias,
    KslDb.KSL_DB,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.view("CREATE VIEW KSL_DB.WITHIN_REP_VIEW (EXP_NAME, RUN_NAME, NUM_REPS, START_REP_ID, LAST_REP_ID, STAT_NAME, REP_ID, REP_VALUE) AS SELECT EXP_NAME, RUN_NAME, NUM_REPS, START_REP_ID, LAST_REP_ID, STAT_NAME, REP_ID, AVERAGE AS REP_VALUE FROM KSL_DB.WITHIN_REP_RESPONSE_VIEW UNION SELECT EXP_NAME, RUN_NAME, NUM_REPS, START_REP_ID, LAST_REP_ID, STAT_NAME, REP_ID, LAST_VALUE AS REP_VALUE FROM KSL_DB.WITHIN_REP_COUNTER_VIEW")
) {
    companion object {

        /**
         * The reference instance of <code>KSL_DB.WITHIN_REP_VIEW</code>
         */
        val WITHIN_REP_VIEW: WithinRepView = WithinRepView()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<WithinRepViewRecord> = WithinRepViewRecord::class.java

    /**
     * The column <code>KSL_DB.WITHIN_REP_VIEW.EXP_NAME</code>.
     */
    val EXP_NAME: TableField<WithinRepViewRecord, String?> = createField(DSL.name("EXP_NAME"), SQLDataType.VARCHAR(510).nullable(false), this, "")

    /**
     * The column <code>KSL_DB.WITHIN_REP_VIEW.RUN_NAME</code>.
     */
    val RUN_NAME: TableField<WithinRepViewRecord, String?> = createField(DSL.name("RUN_NAME"), SQLDataType.VARCHAR(510).nullable(false), this, "")

    /**
     * The column <code>KSL_DB.WITHIN_REP_VIEW.NUM_REPS</code>.
     */
    val NUM_REPS: TableField<WithinRepViewRecord, Int?> = createField(DSL.name("NUM_REPS"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>KSL_DB.WITHIN_REP_VIEW.START_REP_ID</code>.
     */
    val START_REP_ID: TableField<WithinRepViewRecord, Int?> = createField(DSL.name("START_REP_ID"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>KSL_DB.WITHIN_REP_VIEW.LAST_REP_ID</code>.
     */
    val LAST_REP_ID: TableField<WithinRepViewRecord, Int?> = createField(DSL.name("LAST_REP_ID"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>KSL_DB.WITHIN_REP_VIEW.STAT_NAME</code>.
     */
    val STAT_NAME: TableField<WithinRepViewRecord, String?> = createField(DSL.name("STAT_NAME"), SQLDataType.VARCHAR(510), this, "")

    /**
     * The column <code>KSL_DB.WITHIN_REP_VIEW.REP_ID</code>.
     */
    val REP_ID: TableField<WithinRepViewRecord, Int?> = createField(DSL.name("REP_ID"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>KSL_DB.WITHIN_REP_VIEW.REP_VALUE</code>.
     */
    val REP_VALUE: TableField<WithinRepViewRecord, Double?> = createField(DSL.name("REP_VALUE"), SQLDataType.DOUBLE, this, "")

    private constructor(alias: Name, aliased: Table<WithinRepViewRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<WithinRepViewRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>KSL_DB.WITHIN_REP_VIEW</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>KSL_DB.WITHIN_REP_VIEW</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>KSL_DB.WITHIN_REP_VIEW</code> table reference
     */
    constructor(): this(DSL.name("WITHIN_REP_VIEW"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, WithinRepViewRecord>): this(Internal.createPathAlias(child, key), child, key, WITHIN_REP_VIEW, null)
    override fun getSchema(): Schema? = if (aliased()) null else KslDb.KSL_DB
    override fun `as`(alias: String): WithinRepView = WithinRepView(DSL.name(alias), this)
    override fun `as`(alias: Name): WithinRepView = WithinRepView(alias, this)
    override fun `as`(alias: Table<*>): WithinRepView = WithinRepView(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): WithinRepView = WithinRepView(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): WithinRepView = WithinRepView(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): WithinRepView = WithinRepView(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row8<String?, String?, Int?, Int?, Int?, String?, Int?, Double?> = super.fieldsRow() as Row8<String?, String?, Int?, Int?, Int?, String?, Int?, Double?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (String?, String?, Int?, Int?, Int?, String?, Int?, Double?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (String?, String?, Int?, Int?, Int?, String?, Int?, Double?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
