drob table ksl_db.time_series_response;
drop table ksl_db.histogram;
drop table ksl_db.frequency;
drop table ksl_db.batch_stat;
drop table ksl_db.within_rep_counter_stat;
drop table ksl_db.across_rep_stat;
drop table ksl_db.within_rep_stat;
drop table ksl_db.control;
drop table ksl_db.rv_parameter;
drop table ksl_db.model_element;
drop table ksl_db.simulation_run;
drop table ksl_db.experiment;
drop schema ksl_db restrict;
