/*
 *     The KSL provides a discrete-event simulation library for the Kotlin programming language.
 *     Copyright (C) 2024  Manuel D. Rossetti, rossetti@uark.edu
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package ksl.modeling.station

import ksl.modeling.elements.GeneratorActionIfc
import ksl.modeling.nhpp.NHPPPiecewiseRateFunctionEventGenerator
import ksl.modeling.nhpp.PiecewiseRateFunction
import ksl.modeling.variable.Counter
import ksl.modeling.variable.CounterCIfc
import ksl.simulation.ModelElement

/**
 *  A non-homogeneous Poisson process source: generates arriving QObject
 *  instances at a time-varying rate driven by a [PiecewiseRateFunction], then
 *  injects them into the [StationNetwork]. The companion to [SourceStation]
 *  for non-stationary arrivals.
 *
 *  Internally wraps [NHPPPiecewiseRateFunctionEventGenerator]. The rate
 *  function can be piecewise-constant or piecewise-linear; the most common
 *  case (piecewise-constant rates over fixed-duration intervals) is offered
 *  via [StationNetwork.nhppSource] which takes parallel `durations` and
 *  `rates` arrays. Instances are created by the source and may be marked
 *  (typed, given attributes, or assigned their own value object) via the
 *  supplied [marking] action before they enter the network. Externally
 *  created instances can also be injected by calling [receive] directly.
 *
 *  Typically created via [StationNetwork.nhppSource].
 *
 *  @param network the network this source feeds
 *  @param rateFunction the piecewise rate function
 *  @param firstReceiver the receiver that processes generated instances
 *  @param streamNum the stream number for the underlying NHPP
 *  @param maxArrivals the maximum number of arrivals to generate
 *  @param marking optional action applied to each newly created instance
 *  @param name the name of the station
 */
class NHPPSource internal constructor(
    private val network: StationNetwork,
    rateFunction: PiecewiseRateFunction,
    firstReceiver: QObjectReceiverIfc = NotImplementedReceiver,
    streamNum: Int = 0,
    maxArrivals: Long = Long.MAX_VALUE,
    private val marking: ((ModelElement.QObject) -> Unit)? = null,
    name: String? = null
) : ModelElement(network, name), NetworkIngress, RoutingOutletsIfc {

    override val portName: String
        get() = this.name

    private var myFirstReceiver: QObjectReceiverIfc = firstReceiver

    /** Sets the receiver that processes generated instances. */
    fun firstReceiver(receiver: QObjectReceiverIfc) {
        myFirstReceiver = receiver
    }

    override fun outlets(): List<QObjectReceiverIfc> =
        if (myFirstReceiver === NotImplementedReceiver) emptyList() else listOf(myFirstReceiver)

    override val hasOnwardRouting: Boolean
        // a source with a marking hook is not dangling: the hook may attach a
        // sender (e.g., a Route) that determines per-instance routing
        get() = myFirstReceiver !== NotImplementedReceiver || marking != null

    private val myNumCreated: Counter = Counter(this, "${this.name}:NumCreated")

    /** The number of instances generated by this source. */
    val numCreated: CounterCIfc
        get() = myNumCreated

    @Suppress("unused")
    private val myGenerator: NHPPPiecewiseRateFunctionEventGenerator =
        NHPPPiecewiseRateFunctionEventGenerator(
            parent = this,
            generatorAction = GeneratorActionIfc { generate() },
            rateFunction = rateFunction,
            streamNum = streamNum,
            maxNumberOfEvents = maxArrivals,
            name = "${this.name}:NHPPGenerator"
        )

    /**
     *  Stops generating further arrivals; the source still accepts externally
     *  injected instances via [receive]. Typically called from a scheduled action
     *  (e.g., a door-closing time) — pairs with the conditional-routing pattern
     *  where in-flight instances also short-circuit to an exit when a model flag
     *  flips.
     */
    fun turnOffGenerator() {
        myGenerator.turnOffGenerator()
    }

    private fun generate() {
        val qObject = QObject()
        marking?.invoke(qObject)
        myNumCreated.increment()
        receive(qObject)
    }

    /**
     *  Receives a QObject as the network's ingress: performs the network entry
     *  bookkeeping and forwards the instance. If the instance carries its own
     *  sender (for example, a class-supplied route), that sender drives the first
     *  hop; otherwise the configured first receiver is used. Generated arrivals
     *  and externally injected instances both flow through here.
     */
    override fun receive(arrivingQObject: QObject) {
        network.objectEntered(arrivingQObject, this, isNew = true)
        val attachedSender = arrivingQObject.sender
        if (attachedSender != null) {
            attachedSender.send(arrivingQObject)
        } else {
            myFirstReceiver.receive(arrivingQObject)
        }
    }
}
