/*
 *     The KSL provides a discrete-event simulation library for the Kotlin programming language.
 *     Copyright (C) 2024  Manuel D. Rossetti, rossetti@uark.edu
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package ksl.modeling.station

import ksl.modeling.elements.EventGenerator
import ksl.modeling.elements.GeneratorActionIfc
import ksl.modeling.variable.Counter
import ksl.modeling.variable.CounterCIfc
import ksl.simulation.ModelElement
import ksl.utilities.random.rvariable.RVariableIfc

/**
 *  A SourceStation generates QObject instances according to an arrival process
 *  and injects them into a [StationNetwork]. It is the self-contained special
 *  case of a [NetworkIngress] that also creates the arriving instances.
 *
 *  Instances are created by the station and may be marked (typed, given
 *  attributes, or assigned their own value object) via the supplied [marking]
 *  action before they enter the network. Externally created instances can also
 *  be injected by calling [receive] directly, which makes the source a true
 *  open boundary.
 *
 *  Typically created via [StationNetwork.source].
 *
 *  @param network the network this source feeds
 *  @param interArrivalRV the time between successive arrivals
 *  @param firstReceiver the receiver that processes generated instances
 *  @param timeUntilFirstRV the time until the first arrival
 *  @param maxArrivals the maximum number of arrivals to generate
 *  @param qObjectClass optional class template applied to each newly created instance
 *  @param marking optional action applied to each newly created instance (after the class)
 *  @param name the name of the station
 */
class SourceStation internal constructor(
    private val network: StationNetwork,
    interArrivalRV: RVariableIfc,
    firstReceiver: QObjectReceiverIfc = NotImplementedReceiver,
    timeUntilFirstRV: RVariableIfc = interArrivalRV,
    maxArrivals: Long = Long.MAX_VALUE,
    private val qObjectClass: QObjectClass? = null,
    private val marking: ((ModelElement.QObject) -> Unit)? = null,
    name: String? = null
) : ModelElement(network, name), NetworkIngress, RoutingOutletsIfc {

    override val portName: String
        get() = this.name

    private var myFirstReceiver: QObjectReceiverIfc = firstReceiver

    /** Sets the receiver that processes generated instances. */
    fun firstReceiver(receiver: QObjectReceiverIfc) {
        myFirstReceiver = receiver
    }

    override fun outlets(): List<QObjectReceiverIfc> =
        if (myFirstReceiver === NotImplementedReceiver) emptyList() else listOf(myFirstReceiver)

    override val hasOnwardRouting: Boolean
        // a source with a marking hook is not dangling: the hook may attach a
        // sender (e.g., a Route) that determines per-instance routing
        get() = myFirstReceiver !== NotImplementedReceiver || qObjectClass?.route != null || marking != null

    private val myNumCreated: Counter = Counter(this, "${this.name}:NumCreated")

    /** The number of instances generated by this source. */
    val numCreated: CounterCIfc
        get() = myNumCreated

    @Suppress("unused")
    private val myGenerator: EventGenerator = EventGenerator(
        parent = this,
        generateAction = GeneratorActionIfc { generate() },
        timeUntilFirstRV = timeUntilFirstRV,
        timeBtwEventsRV = interArrivalRV,
        maxNumberOfEvents = maxArrivals,
        name = "${this.name}:Generator"
    )

    /**
     *  Stops generating further arrivals; the source still accepts externally
     *  injected instances via [receive]. Typically called from a scheduled action
     *  (e.g., a closing time).
     */
    fun turnOffGenerator() {
        myGenerator.turnOffGenerator()
    }

    private fun generate() {
        val qObject = QObject()
        qObjectClass?.apply(qObject)
        marking?.invoke(qObject)
        myNumCreated.increment()
        receive(qObject)
    }

    /**
     *  Receives a QObject as the network's ingress: performs the network entry
     *  bookkeeping and forwards the instance. If the instance carries its own
     *  sender (for example, a class-supplied route), that sender drives the first
     *  hop; otherwise the configured first receiver is used. Generated arrivals
     *  and externally injected instances both flow through here.
     */
    override fun receive(arrivingQObject: QObject) {
        network.objectEntered(arrivingQObject, this, isNew = true)
        val attachedSender = arrivingQObject.sender
        if (attachedSender != null) {
            attachedSender.send(arrivingQObject)
        } else {
            myFirstReceiver.receive(arrivingQObject)
        }
    }
}
